//! Branch and commit standards (charter §6.4): conventional commit format, the
//! restored v1 subject-length budget and body-shape rule (ADR-0020), the
//! no-AI-attribution rule, the no-emoji rule, and the policy-character rule
//! (ADR-0067).
//!
//! Shared by the commit-msg git hook and the git-guard PR-body scan so both
//! planes flag identical content (AC #13). What counts as a violation lives
//! here; whether it blocks, warns, or passes lives in `policy.json`.

use std::sync::OnceLock;

use regex::Regex;

use super::policy::{GitPolicy, PolicyLevel};
use super::Violation;

/// Conventional commit subject: `type(scope)!: description`.
fn conventional_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(r"^(?P<type>[a-z][a-z0-9]*)(\((?P<scope>[^)]+)\))?(?P<bang>!)?: (?P<desc>\S.*)$")
            .expect("valid regex")
    })
}

/// AI attribution trailers and lines (charter §6.4: `Co-Authored-By` AI
/// trailers, "Generated with …" lines, robot emoji).
fn attribution_res() -> &'static [(Regex, &'static str)] {
    static RES: OnceLock<Vec<(Regex, &'static str)>> = OnceLock::new();
    RES.get_or_init(|| {
        vec![
            (
                Regex::new(
                    r"(?i)co-authored-by:.*(claude|anthropic|openai|chatgpt|gpt|gemini|copilot|codex|cursor|devin|aider|fable|\[bot\]|noreply@anthropic)",
                )
                .expect("valid regex"),
                "Co-Authored-By AI trailer",
            ),
            (
                // Require a known AI tool/agent after the phrase, so legitimate
                // prose ("generated with git-cliff", "auto-generated by the build
                // script") passes while AI-attribution lines block. An optional
                // opening bracket/paren covers markdown links (`[Claude Code](…)`)
                // and an optional article covers "generated by an AI".
                Regex::new(
                    r"(?i)generated (with|by)\s+[\[(]?(an?\s+)?(claude|anthropic|openai|chatgpt|gpt|gemini|copilot|codex|cursor|devin|aider|fable|ai\b|artificial intelligence)",
                )
                .expect("valid regex"),
                "\"Generated with/by\" line",
            ),
            (
                Regex::new("\u{1F916}").expect("valid regex"),
                "robot emoji",
            ),
        ]
    })
}

/// Auto-generated subjects exempt from the conventional-format check. `Merge `
/// is intentionally NOT here: a real merge is exempted once, structurally, in
/// `commit_msg` (via `MERGE_HEAD`); a one-parent commit merely NAMED `Merge ...`
/// stays fully checked, closing the subject-spoofing bypass.
const FORMAT_EXEMPT_PREFIXES: &[&str] = &["Revert ", "Reapply ", "fixup!", "squash!"];

/// Check a commit subject against the conventional format
/// `type(scope): description` with `type` from the policy whitelist,
/// imperative description, no trailing period.
///
/// Returns `None` when the subject conforms (or is an exempt auto-generated
/// subject), otherwise the reason it fails.
#[must_use]
pub fn check_commit_format(subject: &str, allowed_types: &[String]) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let Some(caps) = conventional_re().captures(subject) else {
        return Some(format!(
            "subject does not match `type(scope): description` — got {subject:?}"
        ));
    };
    let ctype = &caps["type"];
    if !allowed_types.iter().any(|t| t == ctype) {
        return Some(format!(
            "commit type {ctype:?} is not in the policy whitelist ({})",
            allowed_types.join(", ")
        ));
    }
    if caps["desc"].trim_end().ends_with('.') {
        return Some("subject must not end with a trailing period".to_string());
    }
    None
}

/// Git reads a commit message's first paragraph as its subject, so a second
/// line that is not blank silently joins the subject in `git log --oneline`,
/// changelogs and PR titles. Require a blank line between the subject (the
/// first non-blank line) and anything after it. A subject-only message
/// passes. Returns `None` when the separator is present, otherwise the reason.
#[must_use]
pub fn check_subject_separator(message: &str) -> Option<String> {
    let mut lines = message.lines().skip_while(|l| l.trim().is_empty());
    lines.next()?;
    match lines.next() {
        Some(second) if !second.trim().is_empty() => Some(format!(
            "the line after the subject must be blank; git reads {:?} as part of the subject",
            second.trim_end()
        )),
        _ => None,
    }
}

/// A Conventional-Commits breaking-change footer must be exactly
/// `BREAKING CHANGE:` or `BREAKING-CHANGE:` (uppercase) to be recognized by
/// versioning tooling (git-cliff, release-please, ...). A mis-cased footer
/// (`breaking change:`) is silently treated as non-breaking — so a MAJOR change
/// would ship as a MINOR bump. Flag it, so the only ways to signal a breaking
/// change are both unambiguous: the subject `!` marker, or the exact footer.
///
/// Skipped when the subject already carries `!` (breaking is already signaled;
/// a "breaking change" line in the body is then just prose). Returns `None` when
/// clean, otherwise the reason.
#[must_use]
pub fn check_breaking_footer(subject: &str, message: &str) -> Option<String> {
    if conventional_re()
        .captures(subject)
        .is_some_and(|c| c.name("bang").is_some())
    {
        return None;
    }
    for line in message.lines() {
        // A footer sits at column 0 (no indentation) — matching what versioning
        // tooling (git-cliff and similar) actually recognizes; an indented line
        // is not a footer, so it is neither a breaking signal nor a mis-case.
        let lower = line.to_ascii_lowercase();
        let token_len = if lower.starts_with("breaking change") {
            "breaking change".len()
        } else if lower.starts_with("breaking-change") {
            "breaking-change".len()
        } else {
            continue;
        };
        // A footer is `token:` — require the colon (after optional spaces).
        if !line[token_len..].trim_start().starts_with(':') {
            continue;
        }
        let token = &line[..token_len];
        if token != "BREAKING CHANGE" && token != "BREAKING-CHANGE" {
            return Some(format!(
                "breaking-change footer {token:?} must be exactly `BREAKING CHANGE:` or \
                 `BREAKING-CHANGE:` (uppercase) to register as a breaking change — \
                 otherwise it is silently treated as non-breaking"
            ));
        }
    }
    None
}

/// Check the subject-line length budget (ADR-0020, the restored v1 standard):
/// the description — the text after `type(scope): ` — must be ≤ `desc_max`, and
/// the whole subject line ≤ `subject_max`. Both are measured in Unicode scalar
/// values (`chars`).
///
/// Auto-generated subjects (merge/revert/fixup/squash) are exempt as a class.
/// A subject that does not parse as conventional returns `None` here —
/// [`check_commit_format`] already reports the malformed shape, so length is not
/// double-reported. Returns `None` when both lengths are within budget,
/// otherwise the reason.
#[must_use]
pub fn check_subject_length(subject: &str, desc_max: u32, subject_max: u32) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let Some(caps) = conventional_re().captures(subject) else {
        return None; // malformed subject is check_commit_format's to report
    };
    let desc_len = caps["desc"].chars().count();
    if desc_len > desc_max as usize {
        return Some(format!(
            "commit description is {desc_len} chars, over the {desc_max}-char limit \
             (measured after `type(scope): `)"
        ));
    }
    let subject_len = subject.chars().count();
    if subject_len > subject_max as usize {
        return Some(format!(
            "commit subject line is {subject_len} chars, over the {subject_max}-char limit"
        ));
    }
    None
}

/// `true` when `line` starts the sanctioned Conventional-Commits breaking-change
/// footer block — `BREAKING CHANGE:` or `BREAKING-CHANGE:` at column 0, in any
/// case. Case-insensitive on purpose: a mis-cased footer is recognized here as a
/// footer (so the body-shape check does not double-report it) while
/// [`check_breaking_footer`] separately flags the mis-case under `commit_format`.
fn is_breaking_footer_start(line: &str) -> bool {
    let lower = line.to_ascii_lowercase();
    let token_len = if lower.starts_with("breaking change") {
        "breaking change".len()
    } else if lower.starts_with("breaking-change") {
        "breaking-change".len()
    } else {
        return false;
    };
    line[token_len..].trim_start().starts_with(':')
}

/// Parse a git-trailer footer line into `(token, value)` (ADR-0020 footer/ticket
/// amendment). Two forms are accepted:
/// - `<Token>: <value>` — a colon, one or more spaces/tabs, then a non-empty
///   value.
/// - `<Token> #<value>` — a space then a `#`-prefixed issue ref (value keeps the
///   `#`).
///
/// `<Token>` is a single word of letters, digits, and hyphens (so multi-word
/// prose like `This change: …` never parses as a trailer, and a `key:value` with
/// no space — e.g. a bare `http://…` URL — is not mistaken for one). Returns
/// `None` when the line is not trailer-shaped. Token whitelisting and the
/// `BREAKING CHANGE` footer are handled by the callers, not here.
fn trailer_kv(line: &str) -> Option<(&str, &str)> {
    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        Regex::new(r"^(?P<token>[A-Za-z][A-Za-z0-9-]*)(?::[ \t]+(?P<v1>\S.*)| +(?P<v2>#\S.*))$")
            .expect("valid regex")
    });
    let caps = re.captures(line.trim_end())?;
    let token = caps.name("token")?.as_str();
    let value = caps.name("v1").or_else(|| caps.name("v2"))?.as_str();
    Some((token, value))
}

/// Check the commit *body* shape (ADR-0020, the restored v1 standard plus the
/// footer/ticket amendment). After the subject the body is: optional `- ` bullets
/// (at most `max_bullets`, each a single line ≤ `bullet_max` chars including the
/// marker), then an optional footer block — the `BREAKING CHANGE:` /
/// `BREAKING-CHANGE:` footer (which may carry a wrapping multi-line description),
/// which is ALWAYS allowed, plus any git-trailer line `<Token>: <value>` (or
/// `<Token> #<value>` for an issue ref) whose `<Token>` is in `footer_tokens`.
/// `footer_tokens` is the project's opt-in set (empty by default — the strict
/// baseline is bullets plus `BREAKING CHANGE:` only), so a `Refs:` or
/// `Signed-off-by:` line blocks unless the project opted the token in. Blank lines
/// are allowed anywhere. A prose paragraph, a numbered list, a story-body, or a
/// trailer whose token is not opted in is a violation naming the offending line.
///
/// A trailer value is single-line and cannot span into prose (each body line is
/// checked on its own), so the no-stories guarantee holds. A `- ` bullet that
/// appears *after* a footer trailer is out of order and blocks — bullets come
/// before the footer.
///
/// Auto-generated subjects (merge/revert/fixup/squash) are exempt as a class,
/// mirroring [`check_commit_format`]: their bodies are tool-authored. Merge
/// commits (>1 parent) are additionally excluded upstream by the `--no-merges`
/// CI enumeration and by the `Merge ` subject prefix here.
///
/// `message` is the comment-stripped commit message (subject + body); the
/// subject is its first non-blank line. Returns `None` when the body conforms,
/// otherwise the reason.
#[must_use]
pub fn check_commit_body(
    subject: &str,
    message: &str,
    max_bullets: u32,
    bullet_max: u32,
    footer_tokens: &[String],
) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let mut seen_subject = false;
    let mut bullets: u32 = 0;
    let mut in_footer = false;
    for line in message.lines() {
        if !seen_subject {
            // Skip everything up to and including the subject (first non-blank).
            if !line.trim().is_empty() {
                seen_subject = true;
            }
            continue;
        }
        let content = line.trim_end(); // tolerate CRLF and trailing spaces
        if content.is_empty() {
            continue; // blank lines are always allowed
        }
        if is_breaking_footer_start(content) {
            // The BREAKING CHANGE block runs to the end of the message (its
            // description may wrap across lines); everything from here on is the
            // sanctioned footer, so stop scanning body lines.
            return over_bullet_budget(bullets, max_bullets);
        }
        if let Some((token, _value)) = trailer_kv(content) {
            if footer_tokens.iter().any(|t| t == token) {
                in_footer = true;
                continue;
            }
            return Some(format!(
                "commit body footer trailer {token:?} is not an allowed footer token — only \
                 `BREAKING CHANGE:` is allowed unless the project opts the token in via \
                 git.commit_footer_tokens / commit_ticket_keys / commit_required_footers: \
                 {content:?}"
            ));
        }
        if content.starts_with("- ") {
            if in_footer {
                return Some(format!(
                    "commit body `- ` bullet appears after a footer trailer; put all bullets \
                     before the footer: {content:?}"
                ));
            }
            bullets += 1;
            let len = content.chars().count();
            if len > bullet_max as usize {
                return Some(format!(
                    "commit body bullet is {len} chars, over the {bullet_max}-char limit: \
                     {content:?}"
                ));
            }
            continue;
        }
        return Some(format!(
            "commit body line is not a `- ` bullet, a footer trailer, or a BREAKING CHANGE \
             footer: {content:?}"
        ));
    }
    over_bullet_budget(bullets, max_bullets)
}

/// Enforce the ticket-reference footer with the allow-vs-require split (ADR-0020
/// footer/ticket amendment). `ticket_keys` names the ticket tokens the project
/// recognizes; when empty the feature is off and this returns `None` (a stray
/// `Refs:` is then blocked by the body-shape check, which does not allow it).
///
/// With `ticket_keys` non-empty:
/// - a present ticket trailer is *allowed* (the body-shape check recognizes the
///   token via
///   [`GitPolicy::allowed_footer_tokens`](super::policy::GitPolicy::allowed_footer_tokens));
/// - when `required` is `warn`/`block`, at least one *matching* ticket trailer
///   must be present — else a violation at the `required` level;
/// - when `pattern` is non-empty, a present ticket trailer whose value does not
///   match is a malformed reference and blocks (level `Block`) even when a ticket
///   is not required — a botched reference is unambiguously wrong.
///
/// Merge/revert/fixup/squash commits are exempt as a class. An unparseable
/// `pattern` degrades to no format check (fail-open, matching the private
/// `path_matches_glob` helper). Returns `Some((level, reason))` for the single most
/// relevant finding, else `None`.
#[must_use]
pub fn check_commit_ticket(
    subject: &str,
    message: &str,
    ticket_keys: &[String],
    required: PolicyLevel,
    pattern: &str,
) -> Option<(PolicyLevel, String)> {
    if ticket_keys.is_empty()
        || FORMAT_EXEMPT_PREFIXES
            .iter()
            .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let re = (!pattern.is_empty())
        .then(|| Regex::new(pattern))
        .and_then(Result::ok);
    let mut present_any = false;
    let mut present_matching = false;
    let mut malformed: Option<String> = None;
    for line in message.lines() {
        let Some((token, value)) = trailer_kv(line.trim_end()) else {
            continue;
        };
        if !ticket_keys.iter().any(|k| k == token) {
            continue;
        }
        present_any = true;
        match &re {
            Some(re) if !re.is_match(value) => {
                if malformed.is_none() {
                    malformed = Some(value.to_string());
                }
            }
            _ => present_matching = true,
        }
    }
    // Required, but no *matching* ticket trailer present (none at all, or every
    // present one is malformed): report at the configured `required` level.
    if required.is_active() && !present_matching {
        let reason = if present_any {
            format!(
                "commit requires a ticket reference matching /{pattern}/ — the present one does not \
                 (keys: {})",
                ticket_keys.join(", ")
            )
        } else {
            format!(
                "this project requires a ticket reference — add a footer trailer such as \
                 `Refs: <id>` (keys: {})",
                ticket_keys.join(", ")
            )
        };
        return Some((required, reason));
    }
    // Optional-but-present: a present ticket whose value fails the pattern is a
    // malformed reference and blocks regardless of the (off) requirement.
    if let Some(bad) = malformed {
        return Some((
            PolicyLevel::Block,
            format!("malformed ticket reference {bad:?} — value must match /{pattern}/"),
        ));
    }
    None
}

/// Every token in `required_footers` must appear as a body footer trailer of the
/// non-exempt commit (ADR-0020 footer/ticket amendment — the DCO `Signed-off-by`
/// case). Merge/revert/fixup/squash commits are exempt as a class. Returns the
/// first missing token's reason, else `None`. A required token is implicitly
/// allowed by the body-shape check (see
/// [`GitPolicy::allowed_footer_tokens`](super::policy::GitPolicy::allowed_footer_tokens)).
#[must_use]
pub fn check_required_footers(
    subject: &str,
    message: &str,
    required_footers: &[String],
) -> Option<String> {
    if required_footers.is_empty()
        || FORMAT_EXEMPT_PREFIXES
            .iter()
            .any(|p| subject.starts_with(p))
    {
        return None;
    }
    required_footers.iter().find_map(|token| {
        let present = message
            .lines()
            .filter_map(|line| trailer_kv(line.trim_end()))
            .any(|(t, _)| t == token);
        (!present).then(|| format!("commit is missing the required footer trailer `{token}:`"))
    })
}

/// `Some(reason)` when the running bullet count exceeds the budget, else `None`.
fn over_bullet_budget(bullets: u32, max_bullets: u32) -> Option<String> {
    (bullets > max_bullets)
        .then(|| format!("commit body has {bullets} bullets, over the {max_bullets}-bullet limit"))
}

/// `true` when the commit already carries a breaking-change *marker* — a `!`
/// after the type/scope in the subject, or a `BREAKING CHANGE:` /
/// `BREAKING-CHANGE:` footer (recognized in any case for the marker test; the
/// exact-case requirement is enforced separately by [`check_breaking_footer`]).
///
/// Used by the contract-surface tripwire (ADR-0020): a commit touching a
/// declared surface without any marker earns a warn.
#[must_use]
pub fn breaking_marker_present(subject: &str, message: &str) -> bool {
    if conventional_re()
        .captures(subject)
        .is_some_and(|c| c.name("bang").is_some())
    {
        return true;
    }
    message.lines().any(is_breaking_footer_start)
}

/// The first entry of `changed_files` that matches one of the `watch_globs`
/// (the `glob` crate's path syntax, same as branch/ignore globs), or `None`
/// when the glob list is empty or nothing matches. The tripwire's file test
/// (ADR-0020): a declared contract surface was touched.
#[must_use]
pub fn first_watched_path<'a>(
    changed_files: &'a [String],
    watch_globs: &[String],
) -> Option<&'a str> {
    if watch_globs.is_empty() {
        return None;
    }
    changed_files
        .iter()
        .find(|f| watch_globs.iter().any(|g| path_matches_glob(g, f)))
        .map(String::as_str)
}

/// `true` when `path` matches the glob `pattern`. An unparseable pattern never
/// matches (fail-open for a malformed user glob — the tripwire is advisory).
fn path_matches_glob(pattern: &str, path: &str) -> bool {
    glob::Pattern::new(pattern).is_ok_and(|p| p.matches(path))
}

/// Scan text (commit message or PR body) for AI attribution.
///
/// Returns the human-readable name of the matched pattern, or `None` when
/// the text is clean.
#[must_use]
pub fn find_attribution(text: &str) -> Option<&'static str> {
    attribution_res()
        .iter()
        .find(|(re, _)| re.is_match(text))
        .map(|(_, name)| *name)
}

/// Find the first emoji character in `text` (commit subject or PR body).
///
/// Covers the emoji presentation blocks plus misc-symbols/dingbats — the v1
/// standard is strict, and `block` is the shipped default.
#[must_use]
pub fn find_emoji(text: &str) -> Option<char> {
    text.chars().find(|&c| is_emoji_char(c))
}

/// The characters ADR-0067 keeps out of new text: U+2013 (en dash) and
/// U+2014 (em dash). The hyphen-minus (U+002D) and the minus sign are not
/// policy characters.
pub const POLICY_CHARACTERS: [char; 2] = ['\u{2013}', '\u{2014}'];

/// The fix every policy-character finding names (ADR-0067), shared by the
/// commit-msg hook, the git-guard PR-body scan and `codeflow ci`.
pub const POLICY_CHARACTER_FIX: &str =
    "use a comma, colon, semicolon, parentheses, or a full stop and a new sentence; \
     a hyphen (-) inside a compound word; \"to\" in a range (ADR-0067)";

/// Repository trees whose added lines carry the policy-character rule in
/// `codeflow ci` (ADR-0067). The `.codeflow/.baseline/` mirrors carry the same
/// bytes as these trees and need no entry of their own.
pub const POLICY_CHARACTER_TREES: [&str; 6] = [
    "docs/",
    "project-management/",
    ".claude/skills/",
    ".agents/skills/",
    "assets/base/agents/skills/",
    "assets/base/claude/skills/",
];

/// Whether `path` (repository-relative, `/`-separated) lies under one of the
/// [`POLICY_CHARACTER_TREES`].
#[must_use]
pub fn in_policy_character_tree(path: &str) -> bool {
    POLICY_CHARACTER_TREES
        .iter()
        .any(|tree| path.starts_with(tree))
}

/// Find the first policy character in `text`: its 1-based line number and the
/// character itself.
#[must_use]
pub fn find_policy_character(text: &str) -> Option<(usize, char)> {
    text.lines().enumerate().find_map(|(i, line)| {
        line.chars()
            .find(|c| POLICY_CHARACTERS.contains(c))
            .map(|c| (i + 1, c))
    })
}

/// The policy-character finding for a PR/MR body, or `None` when the rule is
/// inactive or the body is clean. Shared by the git-guard `gh pr create` scan
/// and `codeflow ci`, so both planes report identical content.
#[must_use]
pub fn pr_body_policy_character(policy: &GitPolicy, body: &str) -> Option<Violation> {
    if !policy.policy_characters.is_active() {
        return None;
    }
    let (line, c) = find_policy_character(body)?;
    Some(Violation::new(
        "git.policy_characters",
        policy.policy_characters,
        format!(
            "PR body line {line} contains an {}",
            policy_character_name(c)
        ),
        crate::remedy::PR_POLICY_CHARACTER.remedy(),
    ))
}

/// Human name of a policy character, for findings: `"em dash (U+2014)"`.
#[must_use]
pub fn policy_character_name(c: char) -> String {
    let name = if c == '\u{2013}' {
        "en dash"
    } else {
        "em dash"
    };
    format!("{name} (U+{:04X})", u32::from(c))
}

fn is_emoji_char(c: char) -> bool {
    matches!(u32::from(c),
        0x1F000..=0x1FAFF   // emoji, symbols, pictographs, flags
        | 0x2600..=0x27BF   // misc symbols + dingbats
        | 0x2B00..=0x2BFF   // misc symbols and arrows (stars, heavy arrows)
        | 0xFE0F            // emoji variation selector
        | 0x1FB00..=0x1FBFF // symbols for legacy computing
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn types() -> Vec<String> {
        super::super::policy::GitPolicy::default().commit_types
    }

    /// The default (strict) allowed-footer set — empty, so only bullets and the
    /// `BREAKING CHANGE:` footer pass.
    fn footers() -> Vec<String> {
        super::super::policy::GitPolicy::default().allowed_footer_tokens()
    }

    /// A project that opted the given tokens into the allowed footer set.
    fn allow(tokens: &[&str]) -> Vec<String> {
        tokens.iter().map(|t| (*t).to_string()).collect()
    }

    // -- commit format --

    #[test]
    fn test_format_valid_subjects() {
        for s in [
            "feat(hooks): add git-guard evaluation",
            "fix: handle unborn head",
            "refactor(core)!: split policy loading",
            "chore: bump deps",
        ] {
            assert_eq!(check_commit_format(s, &types()), None, "{s} should pass");
        }
    }

    #[test]
    fn test_format_malformed_subject() {
        assert!(check_commit_format("Added some stuff", &types()).is_some());
        assert!(check_commit_format("feat add thing", &types()).is_some());
        assert!(check_commit_format("feat:missing space", &types()).is_some());
        assert!(check_commit_format("FEAT: shouting type", &types()).is_some());
    }

    #[test]
    fn test_format_unknown_type() {
        let reason = check_commit_format("feet: walk faster", &types()).unwrap();
        assert!(reason.contains("feet"));
        assert!(reason.contains("whitelist"));
    }

    #[test]
    fn test_format_trailing_period() {
        let reason = check_commit_format("feat: add thing.", &types()).unwrap();
        assert!(reason.contains("trailing period"));
    }

    #[test]
    fn test_format_exempt_auto_generated() {
        for s in [
            "Revert \"feat: add thing\"",
            "fixup! feat: add thing",
            "squash! feat: add thing",
        ] {
            assert_eq!(check_commit_format(s, &types()), None, "{s} exempt");
        }
        // a one-parent commit merely NAMED `Merge ...` is NOT exempt here — a
        // real merge is exempted structurally in commit_msg (codex review).
        assert!(check_commit_format("Merge bypass", &types()).is_some());
    }

    #[test]
    fn test_format_respects_policy_whitelist() {
        // Levels and lists come from policy, nothing hardcoded (D7).
        let narrow = vec!["feat".to_string()];
        assert!(check_commit_format("fix: now rejected", &narrow).is_some());
        assert_eq!(check_commit_format("feat: still fine", &narrow), None);
    }

    // -- breaking-change footer --

    #[test]
    fn test_subject_separator_requires_blank_second_line() {
        assert!(check_subject_separator("feat: add x").is_none());
        assert!(check_subject_separator("feat: add x\n").is_none());
        assert!(check_subject_separator("feat: add x\n\n- bullet").is_none());
        assert!(check_subject_separator("\nfeat: add x\n\n- bullet").is_none());
        let reason = check_subject_separator("feat: add x\n- bullet").unwrap();
        assert!(reason.contains("must be blank"), "{reason}");
        assert!(check_subject_separator("feat: add x\r\n- bullet\r\n").is_some());
        assert!(check_subject_separator("").is_none());
    }

    #[test]
    fn test_breaking_footer_exact_forms_pass() {
        for msg in [
            "feat: add x\n\nBREAKING CHANGE: removes y",
            "feat: add x\n\nBREAKING-CHANGE: removes y",
        ] {
            assert_eq!(check_breaking_footer("feat: add x", msg), None, "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_miscased_flagged() {
        for msg in [
            "feat: add x\n\nbreaking change: removes y",
            "feat: add x\n\nBreaking Change: removes y",
            "feat: add x\n\nbreaking-change: removes y",
        ] {
            assert!(check_breaking_footer("feat: add x", msg).is_some(), "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_bang_subject_exempt() {
        // subject already signals breaking with `!`; a body mention is just prose
        let msg = "feat!: add x\n\nbreaking change: mentioned in prose";
        assert_eq!(check_breaking_footer("feat!: add x", msg), None);
    }

    #[test]
    fn test_breaking_footer_prose_not_flagged() {
        // "breaking change" not at footer position (line start + colon) is prose
        let msg = "fix: thing\n\nThis is not a breaking change: really";
        assert_eq!(check_breaking_footer("fix: thing", msg), None);
    }

    #[test]
    fn test_breaking_footer_non_footer_forms_not_flagged() {
        // Only a column-0 `breaking change:` / `breaking-change:` footer counts.
        for msg in [
            "feat: add x\n\nBREAKING CHANGES: plural is not the footer token",
            "feat: add x\n\nSome BREAKING CHANGE: not at line start",
            "feat: add x\n\n    breaking change: indented is not a footer",
            "feat: add x\n\n- breaking change: a list item",
        ] {
            assert_eq!(check_breaking_footer("feat: add x", msg), None, "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_crlf() {
        // `lines()` strips the trailing `\r`, so CRLF footers are handled.
        assert_eq!(
            check_breaking_footer("feat: x", "feat: x\r\n\r\nBREAKING CHANGE: y\r\n"),
            None
        );
        assert!(
            check_breaking_footer("feat: x", "feat: x\r\n\r\nbreaking change: y\r\n").is_some()
        );
    }

    // -- subject length (ADR-0020) --

    #[test]
    fn test_subject_length_within_budget_passes() {
        assert_eq!(
            check_subject_length("feat(hooks): restore the commit standard", 50, 72),
            None
        );
    }

    #[test]
    fn test_subject_length_desc_over_50_blocked() {
        // Description (after `type: `) is 51 chars — one over the 50 budget,
        // while the whole subject line is still under 72.
        let desc = "a".repeat(51);
        let subject = format!("fix: {desc}");
        let reason = check_subject_length(&subject, 50, 72).unwrap();
        assert!(reason.contains("description"), "{reason}");
        assert!(reason.contains("51"), "{reason}");
        assert!(reason.contains("50"), "{reason}");
    }

    #[test]
    fn test_subject_length_whole_line_over_72_blocked() {
        // Keep the description within 50 but push the whole line past 72 with a
        // long scope, so the subject-line check (not the description check) fires.
        let scope = "s".repeat(30);
        let subject = format!("refactor({scope}): {}", "d".repeat(40));
        assert!(subject.chars().count() > 72);
        assert!("d".repeat(40).chars().count() <= 50);
        let reason = check_subject_length(&subject, 50, 72).unwrap();
        assert!(reason.contains("subject line"), "{reason}");
        assert!(reason.contains("72"), "{reason}");
    }

    #[test]
    fn test_subject_length_exempt_and_malformed_pass() {
        // Merge/revert subjects are exempt as a class; a malformed subject is
        // check_commit_format's to report, not double-reported here.
        let long = "x".repeat(100);
        assert_eq!(check_subject_length(&format!("Merge {long}"), 50, 72), None);
        assert_eq!(
            check_subject_length(&format!("not conventional {long}"), 50, 72),
            None
        );
    }

    // -- commit body shape (ADR-0020) --

    #[test]
    fn test_body_none_and_bullets_pass() {
        // No body at all, and a conforming bullet body, both pass.
        assert_eq!(
            check_commit_body("feat: x", "feat: x", 3, 72, &footers()),
            None
        );
        let msg = "feat: x\n\n- first note\n- second note\n- third note";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72, &footers()), None);
    }

    #[test]
    fn test_body_blank_lines_allowed() {
        let msg = "feat: x\n\n- one\n\n- two\n";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72, &footers()), None);
    }

    #[test]
    fn test_body_paragraph_prose_blocked() {
        let msg = "feat: x\n\nThis is a prose paragraph explaining why.";
        let reason = check_commit_body("feat: x", msg, 3, 72, &footers()).unwrap();
        assert!(reason.contains("not a `- ` bullet"), "{reason}");
        assert!(reason.contains("prose paragraph"), "{reason}");
    }

    #[test]
    fn test_body_four_bullets_blocked() {
        let msg = "feat: x\n\n- one\n- two\n- three\n- four";
        let reason = check_commit_body("feat: x", msg, 3, 72, &footers()).unwrap();
        assert!(reason.contains('4'), "{reason}");
        assert!(reason.contains("bullet"), "{reason}");
    }

    #[test]
    fn test_body_bullet_over_limit_blocked() {
        let long = format!("- {}", "w".repeat(80));
        let msg = format!("feat: x\n\n{long}");
        let reason = check_commit_body("feat: x", &msg, 3, 72, &footers()).unwrap();
        assert!(reason.contains("over the 72-char limit"), "{reason}");
    }

    #[test]
    fn test_body_breaking_footer_block_allowed() {
        // Bullets then a (possibly multi-line) BREAKING CHANGE footer block.
        let msg =
            "feat: x\n\n- one\n\nBREAKING CHANGE: the old api is gone\nsee the migration guide";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72, &footers()), None);
        // The dashed spelling is equally sanctioned.
        let msg2 = "feat: x\n\n- one\n\nBREAKING-CHANGE: gone";
        assert_eq!(check_commit_body("feat: x", msg2, 3, 72, &footers()), None);
    }

    #[test]
    fn test_body_merge_and_revert_exempt() {
        // Revert/fixup/squash carry tool-authored bodies — exempt as a class.
        let revert = "Revert \"feat: x\"\n\nThis reverts commit abc123.";
        assert_eq!(
            check_commit_body("Revert \"feat: x\"", revert, 3, 72, &footers()),
            None
        );
        // A `Merge ...` subject is NOT body-exempt here — a real merge is
        // exempted structurally in commit_msg; a fake one is fully checked.
        let fake_merge = "Merge bypass\n\nA paragraph a fake-merge commit smuggled in.";
        assert!(check_commit_body("Merge bypass", fake_merge, 3, 72, &footers()).is_some());
    }

    // -- commit body footer trailers: strict default + opt-in (ADR-0020) --

    #[test]
    fn test_body_trailers_block_by_default() {
        // Strict baseline: with no opted-in tokens, standard git trailers BLOCK —
        // only bullets and the BREAKING CHANGE footer are allowed.
        for msg in [
            "feat: x\n\n- do it\n\nRefs: PROJ-142",
            "fix: y\n\nCloses: #45",
            "fix: y\n\nCloses #45",
            "chore: z\n\nSigned-off-by: Ada Lovelace <ada@example.com>",
        ] {
            let subject = msg.lines().next().unwrap();
            let reason = check_commit_body(subject, msg, 3, 72, &footers())
                .unwrap_or_else(|| panic!("{msg:?} should block by default"));
            assert!(reason.contains("not an allowed footer token"), "{reason}");
        }
    }

    #[test]
    fn test_body_opted_in_trailer_passes() {
        // A project that opts a token in gets it recognized; a still-unlisted
        // token in the same body blocks.
        let allow = allow(&["Signed-off-by", "Refs"]);
        assert_eq!(
            check_commit_body(
                "feat: x",
                "feat: x\n\n- do it\n\nSigned-off-by: Ada <ada@example.com>\nRefs: PROJ-1",
                3,
                72,
                &allow,
            ),
            None
        );
        // `Reviewed-by` was not opted in → blocks.
        let reason = check_commit_body(
            "feat: x",
            "feat: x\n\nReviewed-by: Grace <grace@example.com>",
            3,
            72,
            &allow,
        )
        .unwrap();
        assert!(reason.contains("Reviewed-by"), "{reason}");
    }

    #[test]
    fn test_body_issue_ref_forms_pass_when_opted_in() {
        let allow = allow(&["Closes"]);
        for msg in ["fix: y\n\nCloses: #45", "fix: y\n\nCloses #45"] {
            assert_eq!(
                check_commit_body("fix: y", msg, 3, 72, &allow),
                None,
                "{msg:?}"
            );
        }
    }

    #[test]
    fn test_body_unknown_trailer_token_blocked() {
        // A trailer-shaped line whose token is not opted in blocks, naming it.
        let msg = "feat: x\n\nNote: this is a sneaky prose line";
        let reason = check_commit_body("feat: x", msg, 3, 72, &footers()).unwrap();
        assert!(reason.contains("Note"), "{reason}");
        assert!(reason.contains("not an allowed footer token"), "{reason}");
    }

    #[test]
    fn test_body_coauthor_only_passes_shape_when_opted_in() {
        // By default Co-authored-by is NOT allowed — it blocks on shape (human or
        // AI alike).
        let human = "feat: x\n\nCo-authored-by: Ada Lovelace <ada@example.com>";
        assert!(check_commit_body("feat: x", human, 3, 72, &footers()).is_some());
        // A project may opt the token in; then the body shape accepts it and the
        // AI/human distinction is ai_attribution's job.
        let allow = allow(&["Co-authored-by"]);
        assert_eq!(check_commit_body("feat: x", human, 3, 72, &allow), None);
        assert_eq!(find_attribution(human), None);
        // An AI value passes the shape (token opted in) but STILL blocks via
        // ai_attribution — the two checks are orthogonal.
        let ai = "feat: x\n\nCo-authored-by: Claude Fable 5 <noreply@anthropic.com>";
        assert_eq!(
            check_commit_body("feat: x", ai, 3, 72, &allow),
            None,
            "opted-in token passes the shape check"
        );
        assert_eq!(find_attribution(ai), Some("Co-Authored-By AI trailer"));
    }

    #[test]
    fn test_body_prose_with_colon_still_blocked() {
        // A prose line that merely contains a colon is not a trailer (its token
        // would be multi-word) — it still blocks.
        let msg = "feat: x\n\nThis change: refactors the parser and adds a test";
        let reason = check_commit_body("feat: x", msg, 3, 72, &footers()).unwrap();
        assert!(reason.contains("not a `- ` bullet"), "{reason}");
    }

    #[test]
    fn test_body_bullet_after_trailer_blocked() {
        // Bullets come before the footer; a bullet after a trailer is out of order.
        let allow = allow(&["Refs"]);
        let msg = "feat: x\n\nRefs: PROJ-1\n- a late bullet";
        let reason = check_commit_body("feat: x", msg, 3, 72, &allow).unwrap();
        assert!(reason.contains("after a footer trailer"), "{reason}");
    }

    // -- required footers (DCO / sign-off) --

    #[test]
    fn test_required_footer_missing_blocks() {
        let required = allow(&["Signed-off-by"]);
        let reason = check_required_footers("feat: x", "feat: x\n\n- do it", &required).unwrap();
        assert!(reason.contains("Signed-off-by"), "{reason}");
        assert!(reason.contains("missing"), "{reason}");
    }

    #[test]
    fn test_required_footer_present_passes() {
        let required = allow(&["Signed-off-by"]);
        let msg = "feat: x\n\n- do it\n\nSigned-off-by: Ada <ada@example.com>";
        assert_eq!(check_required_footers("feat: x", msg, &required), None);
    }

    #[test]
    fn test_required_footer_empty_and_exempt_pass() {
        assert_eq!(check_required_footers("feat: x", "feat: x", &[]), None);
        let required = allow(&["Signed-off-by"]);
        assert_eq!(
            check_required_footers("Revert \"x\"", "Revert \"x\"", &required),
            None
        );
    }

    // -- commit ticket: allow vs require (ADR-0020 footer/ticket amendment) --

    fn keys() -> Vec<String> {
        allow(&["Refs", "Closes"])
    }

    #[test]
    fn test_ticket_feature_off_when_keys_empty() {
        // No keys configured → the ticket check is inert (body-shape blocks a
        // stray `Refs:` separately).
        assert_eq!(
            check_commit_ticket(
                "feat: x",
                "feat: x\n\nRefs: PROJ-1",
                &[],
                PolicyLevel::Block,
                ""
            ),
            None
        );
    }

    #[test]
    fn test_ticket_optional_present_and_absent_pass() {
        // required=Off: a present ticket passes AND an absent one is fine.
        let present = check_commit_ticket(
            "feat: x",
            "feat: x\n\nRefs: PROJ-1",
            &keys(),
            PolicyLevel::Off,
            "",
        );
        assert_eq!(present, None);
        let absent = check_commit_ticket(
            "feat: x",
            "feat: x\n\n- do it",
            &keys(),
            PolicyLevel::Off,
            "",
        );
        assert_eq!(absent, None);
    }

    #[test]
    fn test_ticket_required_absent_blocks_present_passes() {
        let absent = check_commit_ticket(
            "feat: x",
            "feat: x\n\n- do it",
            &keys(),
            PolicyLevel::Block,
            "",
        );
        let (level, reason) = absent.expect("required ticket missing must block");
        assert_eq!(level, PolicyLevel::Block);
        assert!(reason.contains("ticket reference"), "{reason}");
        // A present matching ticket satisfies the requirement.
        assert_eq!(
            check_commit_ticket(
                "feat: x",
                "feat: x\n\nRefs: PROJ-1",
                &keys(),
                PolicyLevel::Block,
                ""
            ),
            None
        );
    }

    #[test]
    fn test_ticket_required_warn_level_carries_through() {
        let (level, _) =
            check_commit_ticket("feat: x", "feat: x", &keys(), PolicyLevel::Warn, "").unwrap();
        assert_eq!(level, PolicyLevel::Warn);
    }

    #[test]
    fn test_ticket_pattern_malformed_present_blocks_even_when_optional() {
        // required=Off but a present ticket's value fails the pattern → malformed,
        // blocks at Block level.
        let (level, reason) = check_commit_ticket(
            "feat: x",
            "feat: x\n\nRefs: nope",
            &keys(),
            PolicyLevel::Off,
            r"^PROJ-\d+$",
        )
        .expect("a malformed optional ticket blocks");
        assert_eq!(level, PolicyLevel::Block);
        assert!(reason.contains("malformed"), "{reason}");
        // A matching value passes.
        assert_eq!(
            check_commit_ticket(
                "feat: x",
                "feat: x\n\nRefs: PROJ-42",
                &keys(),
                PolicyLevel::Off,
                r"^PROJ-\d+$",
            ),
            None
        );
    }

    #[test]
    fn test_ticket_required_with_pattern_needs_a_match() {
        // required=Block + pattern: a present-but-nonmatching ticket does not
        // satisfy the requirement.
        let (level, reason) = check_commit_ticket(
            "feat: x",
            "feat: x\n\nRefs: nope",
            &keys(),
            PolicyLevel::Block,
            r"^PROJ-\d+$",
        )
        .unwrap();
        assert_eq!(level, PolicyLevel::Block);
        assert!(reason.contains("PROJ"), "{reason}");
    }

    #[test]
    fn test_ticket_merge_revert_exempt() {
        for subject in ["Revert \"feat: x\"", "fixup! feat: x"] {
            assert_eq!(
                check_commit_ticket(subject, subject, &keys(), PolicyLevel::Block, ""),
                None,
                "{subject} exempt"
            );
        }
    }

    #[test]
    fn test_ticket_unparseable_pattern_degrades_to_no_format_check() {
        // A malformed regex degrades to no format check (fail-open): a present
        // ticket passes, and required still blocks only when none is present.
        let bad = "([unclosed";
        assert_eq!(
            check_commit_ticket(
                "feat: x",
                "feat: x\n\nRefs: anything",
                &keys(),
                PolicyLevel::Off,
                bad
            ),
            None
        );
        assert!(
            check_commit_ticket("feat: x", "feat: x", &keys(), PolicyLevel::Block, bad).is_some()
        );
    }

    // -- breaking marker + contract-surface tripwire (ADR-0020) --

    #[test]
    fn test_breaking_marker_present() {
        assert!(breaking_marker_present("feat!: x", "feat!: x"));
        assert!(breaking_marker_present("feat(core)!: x", "feat(core)!: x"));
        assert!(breaking_marker_present(
            "feat: x",
            "feat: x\n\nBREAKING CHANGE: gone"
        ));
        // The marker test is case-insensitive (exact case is check_breaking_footer's job).
        assert!(breaking_marker_present(
            "feat: x",
            "feat: x\n\nbreaking-change: gone"
        ));
        // No marker.
        assert!(!breaking_marker_present("feat: x", "feat: x\n\n- a note"));
    }

    #[test]
    fn test_first_watched_path() {
        let files = vec![
            "src/lib.rs".to_string(),
            "crates/codeflow-core/src/hooks/policy.rs".to_string(),
        ];
        // Empty globs → never matches (the shipped default is a no-op).
        assert_eq!(first_watched_path(&files, &[]), None);
        // Exact path glob matches.
        let globs = vec!["crates/codeflow-core/src/hooks/policy.rs".to_string()];
        assert_eq!(
            first_watched_path(&files, &globs),
            Some("crates/codeflow-core/src/hooks/policy.rs")
        );
        // A `**` directory glob matches a file beneath it.
        let tree = vec!["assets/base/policy.json".to_string()];
        assert_eq!(
            first_watched_path(&tree, &["assets/base/**".to_string()]),
            Some("assets/base/policy.json")
        );
        // No overlap → None.
        assert_eq!(first_watched_path(&["README.md".to_string()], &globs), None);
    }

    // -- attribution --

    #[test]
    fn test_attribution_co_authored_by_ai() {
        let msg = "feat: x\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>";
        assert_eq!(find_attribution(msg), Some("Co-Authored-By AI trailer"));
    }

    #[test]
    fn test_attribution_generated_with() {
        let body = "Summary\n\nGenerated with [Claude Code](https://claude.com)";
        assert_eq!(find_attribution(body), Some("\"Generated with/by\" line"));
    }

    #[test]
    fn test_attribution_generated_by_named_tool() {
        for body in [
            "Generated with Claude Code",
            "generated by ChatGPT",
            "Generated by an AI assistant",
            "regenerated by GPT-4 from the schema",
        ] {
            assert_eq!(
                find_attribution(body),
                Some("\"Generated with/by\" line"),
                "{body} should block"
            );
        }
    }

    #[test]
    fn test_attribution_generated_prose_allowed() {
        // "generated with/by" is only attribution when a known AI tool follows;
        // legitimate tooling / prose must pass.
        for body in [
            "generated with git-cliff",
            "auto-generated by the build script",
            "regenerated with the new schema",
            "this file is generated by cargo",
        ] {
            assert_eq!(find_attribution(body), None, "{body} should pass");
        }
    }

    #[test]
    fn test_attribution_robot_emoji() {
        assert_eq!(find_attribution("nice \u{1F916} work"), Some("robot emoji"));
    }

    #[test]
    fn test_attribution_human_coauthor_allowed() {
        let msg = "feat: x\n\nCo-Authored-By: Ada Lovelace <ada@example.com>";
        assert_eq!(find_attribution(msg), None);
    }

    #[test]
    fn test_attribution_clean_text() {
        assert_eq!(find_attribution("fix(core): handle empty refs"), None);
    }

    // -- emoji --

    #[test]
    fn test_emoji_detected_in_subject() {
        // One code point per range arm, so dropping any single arm fails a test.
        assert!(find_emoji("feat: ship it \u{1F680}").is_some()); // 0x1F000..=0x1FAFF
        assert!(find_emoji("fix: sparkle \u{2728}").is_some()); // 0x2600..=0x27BF
        assert!(find_emoji("feat: star \u{2B50}").is_some()); // 0x2B00..=0x2BFF (star)
        assert!(find_emoji("feat: legacy \u{1FB00}").is_some()); // 0x1FB00..=0x1FBFF

        // 0xFE0F (emoji variation selector): the ❤️ sequence U+2764 U+FE0F is a
        // real, blockable emoji.
        assert!(find_emoji("fix: heart \u{2764}\u{FE0F}").is_some());
        // U+2764 alone already matches the 0x2600 arm, so pin the 0xFE0F arm
        // independently on a base that no other arm covers: U+25B6 (0x25B6) sits
        // below every arm, so ▶️ (U+25B6 U+FE0F) is detected *only* via 0xFE0F —
        // dropping that arm leaks this real emoji.
        assert_eq!(find_emoji("fix: play \u{25B6}\u{FE0F}"), Some('\u{FE0F}'));
    }

    // -- policy characters (ADR-0067) --

    #[test]
    fn test_policy_character_found_with_line() {
        assert_eq!(
            find_policy_character("feat: a \u{2014} b"),
            Some((1, '\u{2014}'))
        );
        assert_eq!(
            find_policy_character("feat: x\n\n- pages 1\u{2013}3\n"),
            Some((3, '\u{2013}'))
        );
        assert_eq!(policy_character_name('\u{2013}'), "en dash (U+2013)");
        assert_eq!(policy_character_name('\u{2014}'), "em dash (U+2014)");
    }

    #[test]
    fn test_policy_character_hyphen_and_minus_pass() {
        // The hyphen-minus, the minus sign (U+2212), the figure dash (U+2012)
        // and the horizontal bar (U+2015) are not policy characters.
        assert_eq!(find_policy_character("fix: re-run a -> b, x - y"), None);
        assert_eq!(
            find_policy_character("docs: 3 \u{2212} 1 \u{2012} \u{2015}"),
            None
        );
    }

    #[test]
    fn test_policy_character_trees() {
        for path in [
            "docs/decisions/ADR-0067-written-content-policy.md",
            "project-management/tasks/TSK-066.md",
            ".claude/skills/cf-method/SKILL.md",
            ".agents/skills/cf-method/SKILL.md",
            "assets/base/agents/skills/cf-method/SKILL.md",
            "assets/base/claude/skills/cf-reviewer/SKILL.md",
        ] {
            assert!(in_policy_character_tree(path), "{path}");
        }
        for path in [
            "crates/codeflow-cli/src/cmd/ci.rs",
            ".codeflow/.baseline/docs/product.md",
            "assets/base/docs/product.md",
            "README.md",
            "docsx/a.md",
        ] {
            assert!(!in_policy_character_tree(path), "{path}");
        }
    }

    #[test]
    fn test_plain_text_and_arrows_allowed() {
        assert_eq!(find_emoji("feat: rename a -> b"), None);
        assert_eq!(find_emoji("docs: explain → flow"), None); // U+2192 arrow
        assert_eq!(find_emoji("fix: ümlaut handling"), None);
    }
}
