//! Branch and commit standards (charter §6.4): conventional commit format, the
//! restored v1 subject-length budget and body-shape rule (ADR-0020), the
//! no-AI-attribution rule, and the no-emoji rule.
//!
//! Shared by the commit-msg git hook and the git-guard PR-body scan so both
//! planes flag identical content (AC #13). What counts as a violation lives
//! here; whether it blocks, warns, or passes lives in `policy.json`.

use std::sync::OnceLock;

use regex::Regex;

/// Conventional commit subject: `type(scope)!: description`.
fn conventional_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(r"^(?P<type>[a-z][a-z0-9]*)(\((?P<scope>[^)]+)\))?(?P<bang>!)?: (?P<desc>\S.*)$")
            .expect("valid regex")
    })
}

/// AI attribution trailers and lines (charter §6.4: `Co-Authored-By` AI
/// trailers, "Generated with …" lines, robot emoji).
fn attribution_res() -> &'static [(Regex, &'static str)] {
    static RES: OnceLock<Vec<(Regex, &'static str)>> = OnceLock::new();
    RES.get_or_init(|| {
        vec![
            (
                Regex::new(
                    r"(?i)co-authored-by:.*(claude|anthropic|openai|chatgpt|gpt|gemini|copilot|codex|cursor|devin|aider|fable|\[bot\]|noreply@anthropic)",
                )
                .expect("valid regex"),
                "Co-Authored-By AI trailer",
            ),
            (
                // Require a known AI tool/agent after the phrase, so legitimate
                // prose ("generated with git-cliff", "auto-generated by the build
                // script") passes while AI-attribution lines block. An optional
                // opening bracket/paren covers markdown links (`[Claude Code](…)`)
                // and an optional article covers "generated by an AI".
                Regex::new(
                    r"(?i)generated (with|by)\s+[\[(]?(an?\s+)?(claude|anthropic|openai|chatgpt|gpt|gemini|copilot|codex|cursor|devin|aider|fable|ai\b|artificial intelligence)",
                )
                .expect("valid regex"),
                "\"Generated with/by\" line",
            ),
            (
                Regex::new("\u{1F916}").expect("valid regex"),
                "robot emoji",
            ),
        ]
    })
}

/// Auto-generated subjects exempt from the conventional-format check.
const FORMAT_EXEMPT_PREFIXES: &[&str] = &["Merge ", "Revert ", "Reapply ", "fixup!", "squash!"];

/// Check a commit subject against the conventional format
/// `type(scope): description` with `type` from the policy whitelist,
/// imperative description, no trailing period.
///
/// Returns `None` when the subject conforms (or is an exempt auto-generated
/// subject), otherwise the reason it fails.
#[must_use]
pub fn check_commit_format(subject: &str, allowed_types: &[String]) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let Some(caps) = conventional_re().captures(subject) else {
        return Some(format!(
            "subject does not match `type(scope): description` — got {subject:?}"
        ));
    };
    let ctype = &caps["type"];
    if !allowed_types.iter().any(|t| t == ctype) {
        return Some(format!(
            "commit type {ctype:?} is not in the policy whitelist ({})",
            allowed_types.join(", ")
        ));
    }
    if caps["desc"].trim_end().ends_with('.') {
        return Some("subject must not end with a trailing period".to_string());
    }
    None
}

/// A Conventional-Commits breaking-change footer must be exactly
/// `BREAKING CHANGE:` or `BREAKING-CHANGE:` (uppercase) to be recognized by
/// versioning tooling (git-cliff, release-please, ...). A mis-cased footer
/// (`breaking change:`) is silently treated as non-breaking — so a MAJOR change
/// would ship as a MINOR bump. Flag it, so the only ways to signal a breaking
/// change are both unambiguous: the subject `!` marker, or the exact footer.
///
/// Skipped when the subject already carries `!` (breaking is already signaled;
/// a "breaking change" line in the body is then just prose). Returns `None` when
/// clean, otherwise the reason.
#[must_use]
pub fn check_breaking_footer(subject: &str, message: &str) -> Option<String> {
    if conventional_re()
        .captures(subject)
        .is_some_and(|c| c.name("bang").is_some())
    {
        return None;
    }
    for line in message.lines() {
        // A footer sits at column 0 (no indentation) — matching what versioning
        // tooling (git-cliff and similar) actually recognizes; an indented line
        // is not a footer, so it is neither a breaking signal nor a mis-case.
        let lower = line.to_ascii_lowercase();
        let token_len = if lower.starts_with("breaking change") {
            "breaking change".len()
        } else if lower.starts_with("breaking-change") {
            "breaking-change".len()
        } else {
            continue;
        };
        // A footer is `token:` — require the colon (after optional spaces).
        if !line[token_len..].trim_start().starts_with(':') {
            continue;
        }
        let token = &line[..token_len];
        if token != "BREAKING CHANGE" && token != "BREAKING-CHANGE" {
            return Some(format!(
                "breaking-change footer {token:?} must be exactly `BREAKING CHANGE:` or \
                 `BREAKING-CHANGE:` (uppercase) to register as a breaking change — \
                 otherwise it is silently treated as non-breaking"
            ));
        }
    }
    None
}

/// Check the subject-line length budget (ADR-0020, the restored v1 standard):
/// the description — the text after `type(scope): ` — must be ≤ `desc_max`, and
/// the whole subject line ≤ `subject_max`. Both are measured in Unicode scalar
/// values (`chars`).
///
/// Auto-generated subjects (merge/revert/fixup/squash) are exempt as a class.
/// A subject that does not parse as conventional returns `None` here —
/// [`check_commit_format`] already reports the malformed shape, so length is not
/// double-reported. Returns `None` when both lengths are within budget,
/// otherwise the reason.
#[must_use]
pub fn check_subject_length(subject: &str, desc_max: u32, subject_max: u32) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let Some(caps) = conventional_re().captures(subject) else {
        return None; // malformed subject is check_commit_format's to report
    };
    let desc_len = caps["desc"].chars().count();
    if desc_len > desc_max as usize {
        return Some(format!(
            "commit description is {desc_len} chars, over the {desc_max}-char limit \
             (measured after `type(scope): `)"
        ));
    }
    let subject_len = subject.chars().count();
    if subject_len > subject_max as usize {
        return Some(format!(
            "commit subject line is {subject_len} chars, over the {subject_max}-char limit"
        ));
    }
    None
}

/// `true` when `line` starts the sanctioned Conventional-Commits breaking-change
/// footer block — `BREAKING CHANGE:` or `BREAKING-CHANGE:` at column 0, in any
/// case. Case-insensitive on purpose: a mis-cased footer is recognized here as a
/// footer (so the body-shape check does not double-report it) while
/// [`check_breaking_footer`] separately flags the mis-case under `commit_format`.
fn is_breaking_footer_start(line: &str) -> bool {
    let lower = line.to_ascii_lowercase();
    let token_len = if lower.starts_with("breaking change") {
        "breaking change".len()
    } else if lower.starts_with("breaking-change") {
        "breaking-change".len()
    } else {
        return false;
    };
    line[token_len..].trim_start().starts_with(':')
}

/// Check the commit *body* shape (ADR-0020, the restored v1 standard): after the
/// subject, the only sanctioned content is blank lines, `- ` bullets (at most
/// `max_bullets`, each a single line ≤ `bullet_max` chars including the marker),
/// and an optional trailing `BREAKING CHANGE:` / `BREAKING-CHANGE:` footer block.
/// A prose paragraph, a numbered list, a story-body — anything that is not a
/// bullet, a blank line, or the footer — is a violation naming the offending
/// line.
///
/// Auto-generated subjects (merge/revert/fixup/squash) are exempt as a class,
/// mirroring [`check_commit_format`]: their bodies are tool-authored. Merge
/// commits (>1 parent) are additionally excluded upstream by the `--no-merges`
/// CI enumeration and by the `Merge ` subject prefix here.
///
/// `message` is the comment-stripped commit message (subject + body); the
/// subject is its first non-blank line. Returns `None` when the body conforms,
/// otherwise the reason.
#[must_use]
pub fn check_commit_body(
    subject: &str,
    message: &str,
    max_bullets: u32,
    bullet_max: u32,
) -> Option<String> {
    if FORMAT_EXEMPT_PREFIXES
        .iter()
        .any(|p| subject.starts_with(p))
    {
        return None;
    }
    let mut seen_subject = false;
    let mut bullets: u32 = 0;
    for line in message.lines() {
        if !seen_subject {
            // Skip everything up to and including the subject (first non-blank).
            if !line.trim().is_empty() {
                seen_subject = true;
            }
            continue;
        }
        let content = line.trim_end(); // tolerate CRLF and trailing spaces
        if content.is_empty() {
            continue; // blank lines are always allowed
        }
        if is_breaking_footer_start(content) {
            // The footer block runs to the end of the message; everything from
            // here on is the sanctioned footer, so stop scanning body lines.
            return over_bullet_budget(bullets, max_bullets);
        }
        if content.starts_with("- ") {
            bullets += 1;
            let len = content.chars().count();
            if len > bullet_max as usize {
                return Some(format!(
                    "commit body bullet is {len} chars, over the {bullet_max}-char limit: \
                     {content:?}"
                ));
            }
            continue;
        }
        return Some(format!(
            "commit body line is not a `- ` bullet or a BREAKING CHANGE footer: {content:?}"
        ));
    }
    over_bullet_budget(bullets, max_bullets)
}

/// `Some(reason)` when the running bullet count exceeds the budget, else `None`.
fn over_bullet_budget(bullets: u32, max_bullets: u32) -> Option<String> {
    (bullets > max_bullets).then(|| {
        format!("commit body has {bullets} bullets, over the {max_bullets}-bullet limit")
    })
}

/// `true` when the commit already carries a breaking-change *marker* — a `!`
/// after the type/scope in the subject, or a `BREAKING CHANGE:` /
/// `BREAKING-CHANGE:` footer (recognized in any case for the marker test; the
/// exact-case requirement is enforced separately by [`check_breaking_footer`]).
///
/// Used by the contract-surface tripwire (ADR-0020): a commit touching a
/// declared surface without any marker earns a warn.
#[must_use]
pub fn breaking_marker_present(subject: &str, message: &str) -> bool {
    if conventional_re()
        .captures(subject)
        .is_some_and(|c| c.name("bang").is_some())
    {
        return true;
    }
    message.lines().any(is_breaking_footer_start)
}

/// The first entry of `changed_files` that matches one of the `watch_globs`
/// (the `glob` crate's path syntax, same as branch/ignore globs), or `None`
/// when the glob list is empty or nothing matches. The tripwire's file test
/// (ADR-0020): a declared contract surface was touched.
#[must_use]
pub fn first_watched_path<'a>(
    changed_files: &'a [String],
    watch_globs: &[String],
) -> Option<&'a str> {
    if watch_globs.is_empty() {
        return None;
    }
    changed_files
        .iter()
        .find(|f| watch_globs.iter().any(|g| path_matches_glob(g, f)))
        .map(String::as_str)
}

/// `true` when `path` matches the glob `pattern`. An unparseable pattern never
/// matches (fail-open for a malformed user glob — the tripwire is advisory).
fn path_matches_glob(pattern: &str, path: &str) -> bool {
    glob::Pattern::new(pattern).is_ok_and(|p| p.matches(path))
}

/// Scan text (commit message or PR body) for AI attribution.
///
/// Returns the human-readable name of the matched pattern, or `None` when
/// the text is clean.
#[must_use]
pub fn find_attribution(text: &str) -> Option<&'static str> {
    attribution_res()
        .iter()
        .find(|(re, _)| re.is_match(text))
        .map(|(_, name)| *name)
}

/// Find the first emoji character in `text` (commit subject or PR body).
///
/// Covers the emoji presentation blocks plus misc-symbols/dingbats — the v1
/// standard is strict, and `block` is the shipped default.
#[must_use]
pub fn find_emoji(text: &str) -> Option<char> {
    text.chars().find(|&c| is_emoji_char(c))
}

fn is_emoji_char(c: char) -> bool {
    matches!(u32::from(c),
        0x1F000..=0x1FAFF   // emoji, symbols, pictographs, flags
        | 0x2600..=0x27BF   // misc symbols + dingbats
        | 0x2B00..=0x2BFF   // misc symbols and arrows (stars, heavy arrows)
        | 0xFE0F            // emoji variation selector
        | 0x1FB00..=0x1FBFF // symbols for legacy computing
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn types() -> Vec<String> {
        super::super::policy::GitPolicy::default().commit_types
    }

    // -- commit format --

    #[test]
    fn test_format_valid_subjects() {
        for s in [
            "feat(hooks): add git-guard evaluation",
            "fix: handle unborn head",
            "refactor(core)!: split policy loading",
            "chore: bump deps",
        ] {
            assert_eq!(check_commit_format(s, &types()), None, "{s} should pass");
        }
    }

    #[test]
    fn test_format_malformed_subject() {
        assert!(check_commit_format("Added some stuff", &types()).is_some());
        assert!(check_commit_format("feat add thing", &types()).is_some());
        assert!(check_commit_format("feat:missing space", &types()).is_some());
        assert!(check_commit_format("FEAT: shouting type", &types()).is_some());
    }

    #[test]
    fn test_format_unknown_type() {
        let reason = check_commit_format("feet: walk faster", &types()).unwrap();
        assert!(reason.contains("feet"));
        assert!(reason.contains("whitelist"));
    }

    #[test]
    fn test_format_trailing_period() {
        let reason = check_commit_format("feat: add thing.", &types()).unwrap();
        assert!(reason.contains("trailing period"));
    }

    #[test]
    fn test_format_exempt_auto_generated() {
        for s in [
            "Merge branch 'main' into feat/x",
            "Revert \"feat: add thing\"",
            "fixup! feat: add thing",
            "squash! feat: add thing",
        ] {
            assert_eq!(check_commit_format(s, &types()), None, "{s} exempt");
        }
    }

    #[test]
    fn test_format_respects_policy_whitelist() {
        // Levels and lists come from policy, nothing hardcoded (D7).
        let narrow = vec!["feat".to_string()];
        assert!(check_commit_format("fix: now rejected", &narrow).is_some());
        assert_eq!(check_commit_format("feat: still fine", &narrow), None);
    }

    // -- breaking-change footer --

    #[test]
    fn test_breaking_footer_exact_forms_pass() {
        for msg in [
            "feat: add x\n\nBREAKING CHANGE: removes y",
            "feat: add x\n\nBREAKING-CHANGE: removes y",
        ] {
            assert_eq!(check_breaking_footer("feat: add x", msg), None, "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_miscased_flagged() {
        for msg in [
            "feat: add x\n\nbreaking change: removes y",
            "feat: add x\n\nBreaking Change: removes y",
            "feat: add x\n\nbreaking-change: removes y",
        ] {
            assert!(check_breaking_footer("feat: add x", msg).is_some(), "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_bang_subject_exempt() {
        // subject already signals breaking with `!`; a body mention is just prose
        let msg = "feat!: add x\n\nbreaking change: mentioned in prose";
        assert_eq!(check_breaking_footer("feat!: add x", msg), None);
    }

    #[test]
    fn test_breaking_footer_prose_not_flagged() {
        // "breaking change" not at footer position (line start + colon) is prose
        let msg = "fix: thing\n\nThis is not a breaking change: really";
        assert_eq!(check_breaking_footer("fix: thing", msg), None);
    }

    #[test]
    fn test_breaking_footer_non_footer_forms_not_flagged() {
        // Only a column-0 `breaking change:` / `breaking-change:` footer counts.
        for msg in [
            "feat: add x\n\nBREAKING CHANGES: plural is not the footer token",
            "feat: add x\n\nSome BREAKING CHANGE: not at line start",
            "feat: add x\n\n    breaking change: indented is not a footer",
            "feat: add x\n\n- breaking change: a list item",
        ] {
            assert_eq!(check_breaking_footer("feat: add x", msg), None, "{msg}");
        }
    }

    #[test]
    fn test_breaking_footer_crlf() {
        // `lines()` strips the trailing `\r`, so CRLF footers are handled.
        assert_eq!(
            check_breaking_footer("feat: x", "feat: x\r\n\r\nBREAKING CHANGE: y\r\n"),
            None
        );
        assert!(
            check_breaking_footer("feat: x", "feat: x\r\n\r\nbreaking change: y\r\n").is_some()
        );
    }

    // -- subject length (ADR-0020) --

    #[test]
    fn test_subject_length_within_budget_passes() {
        assert_eq!(
            check_subject_length("feat(hooks): restore the commit standard", 50, 72),
            None
        );
    }

    #[test]
    fn test_subject_length_desc_over_50_blocked() {
        // Description (after `type: `) is 51 chars — one over the 50 budget,
        // while the whole subject line is still under 72.
        let desc = "a".repeat(51);
        let subject = format!("fix: {desc}");
        let reason = check_subject_length(&subject, 50, 72).unwrap();
        assert!(reason.contains("description"), "{reason}");
        assert!(reason.contains("51"), "{reason}");
        assert!(reason.contains("50"), "{reason}");
    }

    #[test]
    fn test_subject_length_whole_line_over_72_blocked() {
        // Keep the description within 50 but push the whole line past 72 with a
        // long scope, so the subject-line check (not the description check) fires.
        let scope = "s".repeat(30);
        let subject = format!("refactor({scope}): {}", "d".repeat(40));
        assert!(subject.chars().count() > 72);
        assert!("d".repeat(40).chars().count() <= 50);
        let reason = check_subject_length(&subject, 50, 72).unwrap();
        assert!(reason.contains("subject line"), "{reason}");
        assert!(reason.contains("72"), "{reason}");
    }

    #[test]
    fn test_subject_length_exempt_and_malformed_pass() {
        // Merge/revert subjects are exempt as a class; a malformed subject is
        // check_commit_format's to report, not double-reported here.
        let long = "x".repeat(100);
        assert_eq!(check_subject_length(&format!("Merge {long}"), 50, 72), None);
        assert_eq!(check_subject_length(&format!("not conventional {long}"), 50, 72), None);
    }

    // -- commit body shape (ADR-0020) --

    #[test]
    fn test_body_none_and_bullets_pass() {
        // No body at all, and a conforming bullet body, both pass.
        assert_eq!(check_commit_body("feat: x", "feat: x", 3, 72), None);
        let msg = "feat: x\n\n- first note\n- second note\n- third note";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72), None);
    }

    #[test]
    fn test_body_blank_lines_allowed() {
        let msg = "feat: x\n\n- one\n\n- two\n";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72), None);
    }

    #[test]
    fn test_body_paragraph_prose_blocked() {
        let msg = "feat: x\n\nThis is a prose paragraph explaining why.";
        let reason = check_commit_body("feat: x", msg, 3, 72).unwrap();
        assert!(reason.contains("not a `- ` bullet"), "{reason}");
        assert!(reason.contains("prose paragraph"), "{reason}");
    }

    #[test]
    fn test_body_four_bullets_blocked() {
        let msg = "feat: x\n\n- one\n- two\n- three\n- four";
        let reason = check_commit_body("feat: x", msg, 3, 72).unwrap();
        assert!(reason.contains('4'), "{reason}");
        assert!(reason.contains("bullet"), "{reason}");
    }

    #[test]
    fn test_body_bullet_over_limit_blocked() {
        let long = format!("- {}", "w".repeat(80));
        let msg = format!("feat: x\n\n{long}");
        let reason = check_commit_body("feat: x", &msg, 3, 72).unwrap();
        assert!(reason.contains("over the 72-char limit"), "{reason}");
    }

    #[test]
    fn test_body_breaking_footer_block_allowed() {
        // Bullets then a (possibly multi-line) BREAKING CHANGE footer block.
        let msg = "feat: x\n\n- one\n\nBREAKING CHANGE: the old api is gone\nsee the migration guide";
        assert_eq!(check_commit_body("feat: x", msg, 3, 72), None);
        // The dashed spelling is equally sanctioned.
        let msg2 = "feat: x\n\n- one\n\nBREAKING-CHANGE: gone";
        assert_eq!(check_commit_body("feat: x", msg2, 3, 72), None);
    }

    #[test]
    fn test_body_merge_and_revert_exempt() {
        // Auto-generated subjects carry tool-authored bodies — exempt as a class.
        let merge = "Merge branch 'main'\n\nA paragraph git wrote, not a bullet.";
        assert_eq!(check_commit_body("Merge branch 'main'", merge, 3, 72), None);
        let revert = "Revert \"feat: x\"\n\nThis reverts commit abc123.";
        assert_eq!(check_commit_body("Revert \"feat: x\"", revert, 3, 72), None);
    }

    // -- breaking marker + contract-surface tripwire (ADR-0020) --

    #[test]
    fn test_breaking_marker_present() {
        assert!(breaking_marker_present("feat!: x", "feat!: x"));
        assert!(breaking_marker_present("feat(core)!: x", "feat(core)!: x"));
        assert!(breaking_marker_present(
            "feat: x",
            "feat: x\n\nBREAKING CHANGE: gone"
        ));
        // The marker test is case-insensitive (exact case is check_breaking_footer's job).
        assert!(breaking_marker_present(
            "feat: x",
            "feat: x\n\nbreaking-change: gone"
        ));
        // No marker.
        assert!(!breaking_marker_present("feat: x", "feat: x\n\n- a note"));
    }

    #[test]
    fn test_first_watched_path() {
        let files = vec![
            "src/lib.rs".to_string(),
            "crates/codeflow-core/src/hooks/policy.rs".to_string(),
        ];
        // Empty globs → never matches (the shipped default is a no-op).
        assert_eq!(first_watched_path(&files, &[]), None);
        // Exact path glob matches.
        let globs = vec!["crates/codeflow-core/src/hooks/policy.rs".to_string()];
        assert_eq!(
            first_watched_path(&files, &globs),
            Some("crates/codeflow-core/src/hooks/policy.rs")
        );
        // A `**` directory glob matches a file beneath it.
        let tree = vec!["assets/base/policy.json".to_string()];
        assert_eq!(
            first_watched_path(&tree, &["assets/base/**".to_string()]),
            Some("assets/base/policy.json")
        );
        // No overlap → None.
        assert_eq!(
            first_watched_path(&["README.md".to_string()], &globs),
            None
        );
    }

    // -- attribution --

    #[test]
    fn test_attribution_co_authored_by_ai() {
        let msg = "feat: x\n\nCo-Authored-By: Claude Fable 5 <noreply@anthropic.com>";
        assert_eq!(find_attribution(msg), Some("Co-Authored-By AI trailer"));
    }

    #[test]
    fn test_attribution_generated_with() {
        let body = "Summary\n\nGenerated with [Claude Code](https://claude.com)";
        assert_eq!(find_attribution(body), Some("\"Generated with/by\" line"));
    }

    #[test]
    fn test_attribution_generated_by_named_tool() {
        for body in [
            "Generated with Claude Code",
            "generated by ChatGPT",
            "Generated by an AI assistant",
            "regenerated by GPT-4 from the schema",
        ] {
            assert_eq!(
                find_attribution(body),
                Some("\"Generated with/by\" line"),
                "{body} should block"
            );
        }
    }

    #[test]
    fn test_attribution_generated_prose_allowed() {
        // "generated with/by" is only attribution when a known AI tool follows;
        // legitimate tooling / prose must pass.
        for body in [
            "generated with git-cliff",
            "auto-generated by the build script",
            "regenerated with the new schema",
            "this file is generated by cargo",
        ] {
            assert_eq!(find_attribution(body), None, "{body} should pass");
        }
    }

    #[test]
    fn test_attribution_robot_emoji() {
        assert_eq!(find_attribution("nice \u{1F916} work"), Some("robot emoji"));
    }

    #[test]
    fn test_attribution_human_coauthor_allowed() {
        let msg = "feat: x\n\nCo-Authored-By: Ada Lovelace <ada@example.com>";
        assert_eq!(find_attribution(msg), None);
    }

    #[test]
    fn test_attribution_clean_text() {
        assert_eq!(find_attribution("fix(core): handle empty refs"), None);
    }

    // -- emoji --

    #[test]
    fn test_emoji_detected_in_subject() {
        // One code point per range arm, so dropping any single arm fails a test.
        assert!(find_emoji("feat: ship it \u{1F680}").is_some()); // 0x1F000..=0x1FAFF
        assert!(find_emoji("fix: sparkle \u{2728}").is_some()); // 0x2600..=0x27BF
        assert!(find_emoji("feat: star \u{2B50}").is_some()); // 0x2B00..=0x2BFF (star)
        assert!(find_emoji("feat: legacy \u{1FB00}").is_some()); // 0x1FB00..=0x1FBFF

        // 0xFE0F (emoji variation selector): the ❤️ sequence U+2764 U+FE0F is a
        // real, blockable emoji.
        assert!(find_emoji("fix: heart \u{2764}\u{FE0F}").is_some());
        // U+2764 alone already matches the 0x2600 arm, so pin the 0xFE0F arm
        // independently on a base that no other arm covers: U+25B6 (0x25B6) sits
        // below every arm, so ▶️ (U+25B6 U+FE0F) is detected *only* via 0xFE0F —
        // dropping that arm leaks this real emoji.
        assert_eq!(find_emoji("fix: play \u{25B6}\u{FE0F}"), Some('\u{FE0F}'));
    }

    #[test]
    fn test_plain_text_and_arrows_allowed() {
        assert_eq!(find_emoji("feat: rename a -> b"), None);
        assert_eq!(find_emoji("docs: explain → flow"), None); // U+2192 arrow
        assert_eq!(find_emoji("fix: ümlaut handling"), None);
    }
}
