//! Operator feedback items (issue 75): one item, one file at
//! `project-management/feedback/FB-NNN.md`, its id issued by the shared
//! registry like any other record (`ids::Kind::Fb`).
//!
//! An item keeps the operator's words verbatim and the agent's reading apart
//! from them, and moves by one transition table:
//!
//! ```text
//!   received --placed --in--> placed --closed --evidence--> closed
//!       |                        |                             |
//!       +-- declined --confirmed-by operator --reason ---------+-> (terminal)
//!       +-- superseded --by FB-NNN (also from placed or closed)
//! ```
//!
//! `codeflow validate --docs` checks every item's structure ([`lint`]); the
//! index (`INDEX.md`) is generated on demand by `codeflow feedback list
//! --write`, and a present index that no longer matches the items is a
//! warning, never a failure. Topics come from `[feedback] topics` in
//! `.codeflow/project.toml` ([`crate::scaffold::state::FeedbackConfig`]).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::ids::{is_uid, Kind, RegId};
use crate::scaffold::state::FeedbackConfig;
use crate::scaffold::template::TemplateContext;
use crate::workgraph::allocate::{Allocator, NewRecord};
use crate::workgraph::record_text::{scan_record, section_span, LineKind};
use crate::workgraph::status_verb::{
    append_to_section, replace_if_unchanged, set_frontmatter_value,
};
use crate::workgraph::StoreError;

/// Where feedback items live, from the project root.
pub const FEEDBACK_DIR: &str = "project-management/feedback";

/// The generated index, from the project root.
pub const INDEX_PATH: &str = "project-management/feedback/INDEX.md";

/// A project's own feedback template, used when it is usable.
pub const PROJECT_TEMPLATE: &str = "project-management/templates/feedback.md";

/// The line that marks the index as generated.
pub const INDEX_MARKER: &str =
    "<!-- Generated by `codeflow feedback list --write`; never edit it by hand. -->";

/// Where a piece of feedback was given.
pub const SOURCES: [&str; 4] = ["chat", "pr", "review", "issue"];

/// Every status, in lifecycle order.
pub const STATUSES: [&str; 5] = ["received", "placed", "closed", "declined", "superseded"];

/// The statuses of an item still waiting to be acted on.
pub const OPEN_STATUSES: [&str; 2] = ["received", "placed"];

/// The body sections of an item, in order.
const SECTIONS: [&str; 4] = ["## Verbatim", "## Reading", "## Placement", "## Closure"];

/// One legal move of the status verb.
#[derive(Debug, Clone, Copy)]
pub struct Transition {
    /// The statuses it leaves.
    pub from: &'static [&'static str],
    /// The status it writes.
    pub to: &'static str,
    /// What the command must carry.
    pub needs: &'static str,
}

/// The transition table. Any move it does not list is refused.
pub const TRANSITIONS: [Transition; 4] = [
    Transition {
        from: &["received"],
        to: "placed",
        needs: "--in <TSK-NNN|EPC-NNN|path> (repeatable)",
    },
    Transition {
        from: &["placed"],
        to: "closed",
        needs: "--evidence <ref>",
    },
    Transition {
        from: &["received", "placed"],
        to: "declined",
        needs: "--confirmed-by operator --reason <text>",
    },
    Transition {
        from: &["received", "placed", "closed"],
        to: "superseded",
        needs: "--by <FB-NNN>",
    },
];

/// The transition table as printed with a refusal.
#[must_use]
pub fn transition_table() -> String {
    TRANSITIONS
        .iter()
        .map(|t| format!("  {} -> {}: {}", t.from.join(" | "), t.to, t.needs))
        .collect::<Vec<_>>()
        .join("\n")
}

/// One feedback item as written.
#[derive(Debug, Clone, Default, Serialize, PartialEq, Eq)]
pub struct Item {
    /// Repository-relative path, `/`-separated.
    pub path: String,
    pub id: String,
    pub uid: String,
    pub title: String,
    pub topic: String,
    pub also: Vec<String>,
    pub source: String,
    pub status: String,
    pub placed_in: Vec<String>,
    pub supersedes: Option<String>,
    pub superseded_by: Option<String>,
    pub confirmed_by: Option<String>,
    pub external_refs: Vec<String>,
    pub created: String,
    /// The visible text of each body section, comments left out.
    pub verbatim: String,
    pub reading: String,
    pub placement: String,
    pub closure: String,
}

impl Item {
    /// Whether the item still waits to be acted on.
    #[must_use]
    pub fn is_open(&self) -> bool {
        OPEN_STATUSES.contains(&self.status.as_str())
    }
}

/// The text of a scalar frontmatter value; `None` for an absent or null one.
fn scalar(
    data: &std::collections::HashMap<String, serde_yaml::Value>,
    key: &str,
) -> Option<String> {
    match data.get(key)? {
        serde_yaml::Value::Null => None,
        serde_yaml::Value::String(text) => {
            let text = text.trim();
            (!text.is_empty()).then(|| text.to_string())
        }
        serde_yaml::Value::Number(number) => Some(number.to_string()),
        serde_yaml::Value::Bool(flag) => Some(flag.to_string()),
        _ => Some(String::new()),
    }
}

/// A list frontmatter value; a scalar reads as a list of one.
fn list(
    data: &std::collections::HashMap<String, serde_yaml::Value>,
    key: &str,
) -> Result<Vec<String>, String> {
    match data.get(key) {
        None | Some(serde_yaml::Value::Null) => Ok(Vec::new()),
        Some(serde_yaml::Value::Sequence(values)) => values
            .iter()
            .map(|value| match value {
                serde_yaml::Value::String(text) => Ok(text.trim().to_string()),
                serde_yaml::Value::Number(number) => Ok(number.to_string()),
                _ => Err(format!("{key} must be a list of strings")),
            })
            .collect(),
        Some(serde_yaml::Value::String(text)) => Ok(vec![text.trim().to_string()]),
        Some(_) => Err(format!("{key} must be a list of strings")),
    }
}

/// The visible text of a level-two section: fences kept, comments and the
/// heading left out, trimmed.
fn section_text(content: &str, heading: &str) -> String {
    let lines: Vec<&str> = content.split('\n').collect();
    let scanned = scan_record(&lines);
    let Some((start, end)) = section_span(&scanned, heading) else {
        return String::new();
    };
    scanned[start + 1..end]
        .iter()
        .filter(|line| line.kind != LineKind::Hidden)
        .map(|line| line.visible.trim_end())
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

/// The bytes of the Verbatim section's body (after its heading line, up to
/// the next heading), which nothing rewrites: the operator's words stay as
/// given even when an id they mention is renumbered.
#[must_use]
pub fn verbatim_range(content: &str) -> Option<std::ops::Range<usize>> {
    let lines: Vec<&str> = content.split('\n').collect();
    let scanned = scan_record(&lines);
    let (start, end) = section_span(&scanned, "## Verbatim")?;
    let offset = |line: usize| -> usize {
        lines[..line]
            .iter()
            .map(|text| text.len() + 1)
            .sum::<usize>()
            .min(content.len())
    };
    Some(offset(start + 1)..offset(end))
}

/// Parse one item. Only a missing or broken frontmatter fails; every other
/// problem is left for [`lint`].
///
/// # Errors
///
/// The reason the frontmatter cannot be read.
pub fn parse_item(path: &str, content: &str) -> Result<Item, String> {
    let (data, _) = crate::validate::parse_frontmatter(content.as_bytes())
        .map_err(|error| format!("frontmatter: {error}"))?;
    Ok(Item {
        path: path.to_string(),
        id: scalar(&data, "id").unwrap_or_default(),
        uid: scalar(&data, "uid").unwrap_or_default(),
        title: scalar(&data, "title").unwrap_or_default(),
        topic: scalar(&data, "topic").unwrap_or_default(),
        also: list(&data, "also")?,
        source: scalar(&data, "source").unwrap_or_default(),
        status: scalar(&data, "status").unwrap_or_default(),
        placed_in: list(&data, "placed_in")?,
        supersedes: scalar(&data, "supersedes"),
        superseded_by: scalar(&data, "superseded_by"),
        confirmed_by: scalar(&data, "confirmed_by"),
        external_refs: list(&data, "external_refs")?,
        created: scalar(&data, "created").unwrap_or_default(),
        verbatim: section_text(content, "## Verbatim"),
        reading: section_text(content, "## Reading"),
        placement: section_text(content, "## Placement"),
        closure: section_text(content, "## Closure"),
    })
}

/// The item files under [`FEEDBACK_DIR`]: every Markdown file directly in
/// it except the index, sorted. Empty when the directory is absent.
/// A symbolic link is never followed: the directory is skipped when a part
/// of its path is one, and a linked entry is left out.
#[must_use]
pub fn item_files(root: &Path) -> Vec<PathBuf> {
    let Ok(dir) = contained_path(root, FEEDBACK_DIR) else {
        return Vec::new();
    };
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_ok_and(|kind| kind.is_file()))
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension().is_some_and(|ext| ext == "md")
                && path.file_name().is_some_and(|name| name != "INDEX.md")
        })
        .collect();
    files.sort();
    files
}

/// Whether the project keeps feedback items (the directory exists).
#[must_use]
pub fn tracked(root: &Path) -> bool {
    root.join(FEEDBACK_DIR).is_dir()
}

/// Whether a repository-relative path is a feedback item (`FB-NNN.md`) or
/// the index, directly in [`FEEDBACK_DIR`].
#[must_use]
pub fn is_feedback_path(path: &str) -> bool {
    let Some(name) = path
        .strip_prefix(FEEDBACK_DIR)
        .and_then(|rest| rest.strip_prefix('/'))
    else {
        return false;
    };
    if name == "INDEX.md" {
        return true;
    }
    name.strip_suffix(".md").is_some_and(|stem| {
        RegId::parse(stem).is_some_and(|id| id.kind() == Kind::Fb && id.to_string() == stem)
    })
}

/// `rel` under `root`, refused when a part of it below `root` is a
/// symbolic link or `rel` is not a plain relative path; a part that does
/// not exist yet is allowed. Feedback reads and writes go through it, so a
/// committed link cannot point them outside the repository.
///
/// # Errors
///
/// The reason the path is refused.
pub fn contained_path(root: &Path, rel: &str) -> Result<PathBuf, String> {
    let mut path = root.to_path_buf();
    for component in Path::new(rel).components() {
        match component {
            Component::Normal(name) => path.push(name),
            Component::CurDir => continue,
            _ => return Err(format!("{rel} is not a path inside the repository")),
        }
        if std::fs::symlink_metadata(&path).is_ok_and(|meta| meta.file_type().is_symlink()) {
            return Err(format!(
                "{} is a symbolic link; feedback files are never read or written through one",
                relative(root, &path)
            ));
        }
    }
    Ok(path)
}

/// Write the index generated from the items: refused when the index or a
/// directory above it is a symbolic link, and written to a temporary file
/// beside it that is then renamed over it, so a reader never sees half an
/// index.
///
/// # Errors
///
/// A refused path or an I/O error.
pub fn write_index(root: &Path, content: &str) -> Result<(), String> {
    let path = contained_path(root, INDEX_PATH)?;
    let temporary = path.with_file_name(format!(".INDEX.md.{}.tmp", std::process::id()));
    let written = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .and_then(|mut file| std::io::Write::write_all(&mut file, content.as_bytes()))
        .and_then(|()| std::fs::rename(&temporary, &path));
    written.map_err(|error| {
        let _ = std::fs::remove_file(&temporary);
        format!("cannot write {INDEX_PATH}: {error}")
    })
}

/// Every item the project keeps, and each file that could not be read.
#[derive(Debug, Default)]
pub struct Loaded {
    pub items: Vec<Item>,
    /// `(path, reason)` for each unreadable file.
    pub unreadable: Vec<(String, String)>,
}

/// Read every item.
#[must_use]
pub fn load(root: &Path) -> Loaded {
    let mut loaded = Loaded::default();
    for path in item_files(root) {
        let rel = relative(root, &path);
        match std::fs::read_to_string(&path) {
            Ok(content) => match parse_item(&rel, &content) {
                Ok(item) => loaded.items.push(item),
                Err(reason) => loaded.unreadable.push((rel, reason)),
            },
            Err(error) => loaded.unreadable.push((rel, error.to_string())),
        }
    }
    loaded
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// The project's topics, or the default list when it sets none.
///
/// # Errors
///
/// The reason `[feedback]` cannot be read.
pub fn topics(root: &Path) -> Result<Vec<String>, String> {
    FeedbackConfig::load(root)
        .map(|config| config.topics_or_default())
        .map_err(|error| error.to_string())
}

/// Whether `reference` names a work item or a path that exists: a `TSK-NNN`
/// or `EPC-NNN` record in the checkout, or a repository-relative path (an
/// optional `#anchor` is ignored) that stays inside the repository and
/// reaches its target through no symbolic link.
#[must_use]
pub fn placement_resolves(root: &Path, reference: &str) -> bool {
    let reference = reference.trim();
    if reference.is_empty() {
        return false;
    }
    if let Some(id) = RegId::parse(reference) {
        return matches!(id.kind(), Kind::Tsk | Kind::Epc)
            && crate::workgraph::allocate::work_item_exists(
                &root.join("project-management"),
                reference,
            );
    }
    let path = reference.split('#').next().unwrap_or_default();
    let relative = Path::new(path);
    if path.is_empty()
        || !relative
            .components()
            .all(|component| matches!(component, Component::Normal(_) | Component::CurDir))
    {
        return false;
    }
    contained_path(root, path).is_ok_and(|target| std::fs::symlink_metadata(target).is_ok())
}

fn one_line(value: &str, what: &str) -> Result<String, String> {
    let value = value.trim();
    if value.is_empty() {
        return Err(format!("{what} cannot be empty"));
    }
    if value.contains(['\r', '\n']) {
        return Err(format!("{what} must be one line"));
    }
    Ok(value.to_string())
}

/// Check that `text` is a usable feedback template: it carries the
/// placeholders `feedback new` fills, and an item rendered from it carries
/// them in the fields that own them with `status: received`.
///
/// # Errors
///
/// The first reason it is not usable.
pub fn check_template(text: &str) -> Result<(), String> {
    const PLACEHOLDERS: [&str; 6] = [
        "{{NNN}}",
        "{{UID}}",
        "{{TITLE_YAML}}",
        "{{DATE}}",
        "{{TOPIC_YAML}}",
        "{{SOURCE}}",
    ];
    if let Some(missing) = PLACEHOLDERS.iter().find(|p| !text.contains(**p)) {
        return Err(format!("missing placeholder {missing}"));
    }
    for (nnn, topic, source) in [("986", "process", "chat"), ("987", "null", "review")] {
        let uid = crate::ids::new_uid();
        let rendered = render(
            text,
            nnn,
            &uid,
            "template check",
            topic,
            source,
            "2026-01-01",
        );
        let item = parse_item(&format!("{FEEDBACK_DIR}/FB-{nnn}.md"), &rendered)?;
        let expected = [
            ("id", item.id.as_str(), format!("FB-{nnn}")),
            ("uid", item.uid.as_str(), uid.clone()),
            ("title", item.title.as_str(), "template check".to_string()),
            ("topic", item.topic.as_str(), topic.to_string()),
            ("source", item.source.as_str(), source.to_string()),
            ("status", item.status.as_str(), "received".to_string()),
        ];
        for (field, found, want) in expected {
            if found != want {
                return Err(format!("`{field}` reads {found:?}, not {want:?}"));
            }
        }
        for heading in SECTIONS {
            if !rendered.contains(&format!("\n{heading}\n")) {
                return Err(format!("missing section {heading}"));
            }
        }
    }
    Ok(())
}

fn render(
    template: &str,
    nnn: &str,
    uid: &str,
    title: &str,
    topic: &str,
    source: &str,
    date: &str,
) -> String {
    let title_yaml = yaml_string(title);
    let topic_yaml = yaml_string(topic);
    let mut context = TemplateContext::new();
    for (key, value) in [
        ("NNN", nnn),
        ("UID", uid),
        ("TITLE", title),
        ("TITLE_YAML", title_yaml.as_str()),
        ("TOPIC", topic),
        ("TOPIC_YAML", topic_yaml.as_str()),
        ("SOURCE", source),
        ("DATE", date),
    ] {
        context.set(key, value);
    }
    context.substitute(template)
}

/// Why `topic` is refused, with the list, or `None` when it is listed.
#[must_use]
pub fn topic_refusal(topic: &str, topics: &[String]) -> Option<String> {
    (!topics.iter().any(|known| known == topic)).then(|| {
        format!(
            "topic `{topic}` is not in the project's list: {}; add it to `[feedback] topics` in .codeflow/project.toml to use it",
            topics.join(", ")
        )
    })
}

/// Write a new item with the id and `uid` `allocate` chooses, once its
/// inputs are valid: a listed topic, a known source and a one-line summary.
/// The file is created exclusively.
///
/// # Errors
///
/// An invalid input, the allocator's error, or an I/O error.
pub fn create_with(
    root: &Path,
    template: &str,
    topic: &str,
    source: &str,
    summary: &str,
    topics: &[String],
    allocate: &mut Allocator<'_>,
) -> Result<NewRecord, StoreError> {
    let summary = one_line(summary, "the summary").map_err(StoreError::Invalid)?;
    if let Some(refusal) = topic_refusal(topic, topics) {
        return Err(StoreError::Invalid(refusal));
    }
    if !SOURCES.contains(&source) {
        return Err(StoreError::Invalid(format!(
            "source `{source}` is not one of {}",
            SOURCES.join(", ")
        )));
    }
    let dir = contained_path(root, FEEDBACK_DIR).map_err(StoreError::Invalid)?;
    let pm = root.join("project-management");
    let (id, uid) = allocate(&crate::workgraph::allocate::planning_target(&pm))?;
    let parsed = RegId::parse(&id).filter(|parsed| parsed.kind() == Kind::Fb);
    let Some(parsed) = parsed else {
        return Err(StoreError::Invalid(format!(
            "the allocator returned {id}, not an FB id"
        )));
    };
    let date = crate::ids::today();
    let content = render(
        template,
        parsed.number(),
        &uid,
        &summary,
        topic,
        source,
        &date,
    );
    std::fs::create_dir_all(&dir)?;
    // `create_new` refuses an existing name, a symbolic link included.
    let path = dir.join(format!("{id}.md"));
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&path)?;
    if let Err(error) = std::io::Write::write_all(&mut file, content.as_bytes()) {
        drop(file);
        let _ = std::fs::remove_file(&path);
        return Err(StoreError::Io(error));
    }
    Ok(NewRecord { id, uid, path })
}

/// The next id from the visible checkout, for a project without the
/// registry.
#[must_use]
pub fn next_visible_id(root: &Path) -> String {
    let next = item_files(root)
        .iter()
        .filter_map(|path| path.file_stem()?.to_str().and_then(RegId::parse))
        .filter(|id| id.kind() == Kind::Fb)
        .filter_map(|id| id.seq())
        .max()
        .unwrap_or(0)
        + 1;
    RegId::canonical(Kind::Fb, next).to_string()
}

/// What `feedback status` was asked to do.
#[derive(Debug, Clone, Default)]
pub struct StatusChange {
    /// The requested status.
    pub target: String,
    /// `--in`: where the item is placed.
    pub placements: Vec<String>,
    /// `--evidence`: what closed it.
    pub evidence: Option<String>,
    /// `--confirmed-by`: who confirmed a decline.
    pub confirmed_by: Option<String>,
    /// `--reason`: why it was declined.
    pub reason: Option<String>,
    /// `--by`: the item that supersedes it.
    pub by: Option<String>,
}

/// A written status change.
#[derive(Debug, Clone)]
pub struct StatusOutcome {
    pub path: PathBuf,
    pub from: String,
    pub to: String,
}

fn required<'a>(value: Option<&'a String>, flag: &str, why: &str) -> Result<&'a str, String> {
    value
        .map(|value| value.trim())
        .filter(|value| !value.is_empty() && !value.contains(['\r', '\n']))
        .ok_or_else(|| format!("{why} needs {flag} <one line>"))
}

/// Change one item's status by the transition table; nothing is written on
/// any refusal.
///
/// # Errors
///
/// The refusal, with the table when the move is not in it.
pub fn set_status(root: &Path, id: &str, change: &StatusChange) -> Result<StatusOutcome, String> {
    let Some(parsed) = RegId::parse(id).filter(|parsed| parsed.kind() == Kind::Fb) else {
        return Err(format!("`{id}` is not a feedback id (FB-NNN)"));
    };
    let path = contained_path(root, &format!("{FEEDBACK_DIR}/{parsed}.md"))?;
    let content = std::fs::read_to_string(&path)
        .map_err(|_| format!("{id} not found under {FEEDBACK_DIR}/"))?;
    let rel = relative(root, &path);
    let item = parse_item(&rel, &content)?;
    let from = item.status.clone();
    let target = change.target.as_str();
    if from == target {
        return Err(format!("{id} is already {from}"));
    }
    let legal = TRANSITIONS
        .iter()
        .any(|t| t.to == target && t.from.contains(&from.as_str()));
    if !legal {
        return Err(format!(
            "{id}: {from} -> {target} is not a feedback transition; the table:\n{}",
            transition_table()
        ));
    }
    let proposed = propose(root, &parsed, &item, &content, change)?;
    let digest = Sha256::digest(content.as_bytes());
    replace_if_unchanged(&path, digest.as_slice(), &proposed).map_err(|error| error.to_string())?;
    Ok(StatusOutcome {
        path,
        from,
        to: target.to_string(),
    })
}

/// The item's text after `change`: the status and the lines the move
/// carries, its inputs checked first.
fn propose(
    root: &Path,
    parsed: &RegId,
    item: &Item,
    content: &str,
    change: &StatusChange,
) -> Result<String, String> {
    let id = parsed.to_string();
    let today = crate::ids::today();
    let mut proposed = content.to_string();
    let target = change.target.as_str();
    match target {
        "placed" => {
            if change.placements.is_empty() {
                return Err("placing needs --in <TSK-NNN|EPC-NNN|path>".to_string());
            }
            let mut placed = item.placed_in.clone();
            for reference in &change.placements {
                let reference = one_line(reference, "--in")?;
                if !placement_resolves(root, &reference) {
                    return Err(format!(
                        "--in {reference} does not resolve: name a TSK-NNN or EPC-NNN record in this checkout, or a path inside the repository that exists"
                    ));
                }
                if placed.contains(&reference) {
                    continue;
                }
                proposed = append_to_section(
                    &proposed,
                    "## Placement",
                    &format!("- placed in {reference} ({today})\n"),
                );
                placed.push(reference);
            }
            proposed = set_frontmatter_value(&proposed, "placed_in", &flow_list(&placed))?;
        }
        "closed" => {
            let evidence = required(change.evidence.as_ref(), "--evidence", "closing")?;
            proposed = append_to_section(
                &proposed,
                "## Closure",
                &format!("- closed by {evidence} ({today})\n"),
            );
        }
        "declined" => {
            if change.confirmed_by.as_deref() != Some("operator") {
                return Err(
                    "declining needs --confirmed-by operator: only the operator declines feedback"
                        .to_string(),
                );
            }
            let reason = required(change.reason.as_ref(), "--reason", "declining")?;
            proposed = set_frontmatter_value(&proposed, "confirmed_by", "operator")?;
            proposed = append_to_section(
                &proposed,
                "## Closure",
                &format!("- declined, confirmed by the operator ({today}): {reason}\n"),
            );
        }
        "superseded" => {
            let by = required(change.by.as_ref(), "--by", "superseding")?;
            let successor = RegId::parse(by).filter(|parsed| parsed.kind() == Kind::Fb);
            let Some(successor) = successor else {
                return Err(format!("--by {by} is not a feedback id (FB-NNN)"));
            };
            if &successor == parsed {
                return Err(format!("{id} cannot supersede itself"));
            }
            let successor_path = contained_path(root, &format!("{FEEDBACK_DIR}/{successor}.md"))?;
            if !std::fs::symlink_metadata(&successor_path).is_ok_and(|meta| meta.is_file()) {
                return Err(format!(
                    "--by {successor} does not exist under {FEEDBACK_DIR}/"
                ));
            }
            proposed = set_frontmatter_value(&proposed, "superseded_by", &successor.to_string())?;
            proposed = append_to_section(
                &proposed,
                "## Closure",
                &format!("- superseded by {successor} ({today})\n"),
            );
        }
        _ => {}
    }
    proposed = set_frontmatter_value(&proposed, "status", target)?;
    Ok(proposed)
}

/// `value` as a double-quoted YAML string, so a value such as `true`,
/// `null` or `[ux]` reads back as the same string.
fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_string())
}

/// A YAML flow list of double-quoted strings.
fn flow_list(values: &[String]) -> String {
    let rendered: Vec<String> = values.iter().map(|value| yaml_string(value)).collect();
    format!("[{}]", rendered.join(", "))
}

/// One structural finding, addressable as `file:line`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LintFinding {
    pub path: String,
    pub line: usize,
    pub message: String,
}

/// What [`lint`] found: failures and warnings.
#[derive(Debug, Default)]
pub struct Lint {
    pub errors: Vec<LintFinding>,
    pub warnings: Vec<crate::remedy::Finding>,
}

fn line_of(content: &str, key: &str) -> usize {
    let prefix = format!("{key}:");
    content
        .lines()
        .position(|line| line.starts_with(&prefix))
        .map_or(1, |index| index + 1)
}

/// Check every item's structure (`validate --docs`). Nothing is checked, and
/// nothing reported, when the project keeps no feedback directory.
#[must_use]
pub fn lint(root: &Path) -> Lint {
    let mut lint = Lint::default();
    if !tracked(root) {
        return lint;
    }
    let topics = match topics(root) {
        Ok(topics) => topics,
        Err(error) => {
            lint.errors.push(LintFinding {
                path: crate::scaffold::state::PROJECT_TOML.to_string(),
                line: 1,
                message: format!("feedback topics cannot be read: {error}"),
            });
            FeedbackConfig::default().topics_or_default()
        }
    };
    let loaded = load(root);
    for (path, reason) in &loaded.unreadable {
        lint.errors.push(LintFinding {
            path: path.clone(),
            line: 1,
            message: format!("feedback item cannot be read: {reason}"),
        });
    }
    let ids: BTreeSet<String> = loaded.items.iter().map(|item| item.id.clone()).collect();
    let mut uids: BTreeMap<&str, &str> = BTreeMap::new();
    for item in &loaded.items {
        lint_item(root, item, &topics, &ids, &mut uids, &mut lint.errors);
    }
    if let Err(reason) = contained_path(root, FEEDBACK_DIR) {
        lint.errors.push(LintFinding {
            path: FEEDBACK_DIR.to_string(),
            line: 1,
            message: format!("{reason}; keep the items in the directory itself"),
        });
    }
    let written =
        contained_path(root, INDEX_PATH).and_then(|path| match std::fs::symlink_metadata(&path) {
            Ok(_) => std::fs::read_to_string(path)
                .map(Some)
                .map_err(|e| e.to_string()),
            Err(_) => Ok(None),
        });
    if let Err(reason) = &written {
        lint.warnings.push(crate::remedy::Finding::new(
            format!("{INDEX_PATH} cannot be checked: {reason}"),
            crate::remedy::FEEDBACK_INDEX_STALE.remedy(),
        ));
    }
    if let Ok(Some(written)) = written {
        if loaded.unreadable.is_empty() && written != render_index(&loaded.items, &topics) {
            lint.warnings.push(crate::remedy::Finding::new(
                format!("{INDEX_PATH} does not match the feedback items"),
                crate::remedy::FEEDBACK_INDEX_STALE.remedy(),
            ));
        }
    }
    lint.errors
        .sort_by(|a, b| (&a.path, a.line, &a.message).cmp(&(&b.path, b.line, &b.message)));
    lint
}

/// One item's structure, each finding pushed to `errors`.
fn lint_item<'a>(
    root: &Path,
    item: &'a Item,
    topics: &[String],
    ids: &BTreeSet<String>,
    uids: &mut BTreeMap<&'a str, &'a str>,
    errors: &mut Vec<LintFinding>,
) {
    let content = std::fs::read_to_string(root.join(&item.path)).unwrap_or_default();
    let mut fail = |key: &str, message: String| {
        errors.push(LintFinding {
            path: item.path.clone(),
            line: line_of(&content, key),
            message,
        });
    };
    let stem = Path::new(&item.path)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or_default();
    match RegId::parse(&item.id).filter(|id| id.kind() == Kind::Fb) {
        None => fail("id", format!("id `{}` is not FB-NNN", item.id)),
        Some(id) if id.to_string() != stem => fail(
            "id",
            format!("id {id} disagrees with the file name {stem}.md"),
        ),
        Some(_) => {}
    }
    if !is_uid(&item.uid) {
        fail(
            "uid",
            "uid is not a lower-case UUIDv4 written by `feedback new`".to_string(),
        );
    } else if let Some(first) = uids.insert(item.uid.as_str(), item.path.as_str()) {
        fail(
            "uid",
            format!("uid {} is also carried by {first}", item.uid),
        );
    }
    if item.title.is_empty() {
        fail("title", "title is empty".to_string());
    }
    if !topics.contains(&item.topic) {
        fail(
            "topic",
            format!(
                "topic `{}` is not in the project's list ({})",
                item.topic,
                topics.join(", ")
            ),
        );
    }
    for also in item.also.iter().filter(|also| !topics.contains(also)) {
        fail(
            "also",
            format!("also names `{also}`, which is not a listed topic"),
        );
    }
    if !SOURCES.contains(&item.source.as_str()) {
        fail(
            "source",
            format!(
                "source `{}` is not one of {}",
                item.source,
                SOURCES.join(", ")
            ),
        );
    }
    if !STATUSES.contains(&item.status.as_str()) {
        fail(
            "status",
            format!(
                "status `{}` is not one of {}",
                item.status,
                STATUSES.join(", ")
            ),
        );
    }
    if item.verbatim.is_empty() {
        fail(
            "id",
            "the Verbatim section is empty: quote the operator's words".to_string(),
        );
    }
    lint_links(root, item, ids, &mut fail);
}

/// The checks a status brings, and the references between items.
fn lint_links(
    root: &Path,
    item: &Item,
    ids: &BTreeSet<String>,
    fail: &mut impl FnMut(&str, String),
) {
    match item.status.as_str() {
        "placed" => {
            if item.placed_in.is_empty() {
                fail(
                    "placed_in",
                    "a placed item has no placed_in entry".to_string(),
                );
            }
            for reference in item
                .placed_in
                .iter()
                .filter(|reference| !placement_resolves(root, reference))
            {
                fail(
                    "placed_in",
                    format!("placed_in entry {reference} does not resolve to a task, epic or path"),
                );
            }
        }
        "closed" if item.closure.is_empty() => {
            fail(
                "status",
                "a closed item has an empty Closure section".to_string(),
            );
        }
        "declined" if item.confirmed_by.as_deref() != Some("operator") => {
            fail(
                "confirmed_by",
                "a declined item needs `confirmed_by: operator`".to_string(),
            );
        }
        "superseded" => match item.superseded_by.as_deref() {
            Some(by) if by != item.id && ids.contains(by) => {}
            Some(by) => fail(
                "superseded_by",
                format!("superseded_by {by} does not resolve to another feedback item"),
            ),
            None => fail(
                "superseded_by",
                "a superseded item needs superseded_by".to_string(),
            ),
        },
        _ => {}
    }
    if let Some(previous) = item.supersedes.as_deref() {
        if previous == item.id || !ids.contains(previous) {
            fail(
                "supersedes",
                format!("supersedes {previous} does not resolve to another feedback item"),
            );
        }
    }
}

/// The items grouped by topic in the project's topic order (topics it does
/// not list last, by name), each group open items first, then by id.
#[must_use]
pub fn grouped<'a>(items: &'a [Item], topics: &[String]) -> Vec<(String, Vec<&'a Item>)> {
    let mut groups: BTreeMap<(usize, String), Vec<&Item>> = BTreeMap::new();
    for item in items {
        let rank = topics
            .iter()
            .position(|topic| *topic == item.topic)
            .unwrap_or(topics.len());
        groups
            .entry((rank, item.topic.clone()))
            .or_default()
            .push(item);
    }
    groups
        .into_iter()
        .map(|((_, topic), mut members)| {
            members.sort_by(|a, b| (!a.is_open(), &a.id).cmp(&(!b.is_open(), &b.id)));
            (topic, members)
        })
        .collect()
}

fn cell(text: &str) -> String {
    let first = text
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or("");
    first.trim().replace('|', "\\|")
}

/// The generated index: one table per topic, open items first. It carries
/// no date, so the same items always render the same bytes.
#[must_use]
pub fn render_index(items: &[Item], topics: &[String]) -> String {
    let mut out = String::from("# Operator feedback\n\n");
    out.push_str(INDEX_MARKER);
    out.push('\n');
    let open = items.iter().filter(|item| item.is_open()).count();
    let _ = writeln!(
        out,
        "\n{} item(s), {open} open. Each item is its own file in this folder.",
        items.len()
    );
    for (topic, members) in grouped(items, topics) {
        let _ = write!(
            out,
            "\n## {topic}\n\n| Id | Date | Status | Summary | Placed in | Closure |\n|---|---|---|---|---|---|\n"
        );
        for item in members {
            let _ = writeln!(
                out,
                "| [{id}]({id}.md) | {} | {} | {} | {} | {} |",
                cell(&item.created),
                cell(&item.status),
                cell(&item.title),
                cell(&item.placed_in.join(", ")),
                cell(&item.closure),
                id = item.id,
            );
        }
    }
    out
}

/// Open items by topic, for `codeflow status`; `None` when the project
/// keeps no feedback directory.
#[must_use]
pub fn open_summary(root: &Path) -> Option<(usize, Vec<(String, usize)>)> {
    if !tracked(root) {
        return None;
    }
    let topics = topics(root).unwrap_or_default();
    let loaded = load(root);
    let mut by_topic = Vec::new();
    let mut total = 0;
    for (topic, members) in grouped(&loaded.items, &topics) {
        let open = members.iter().filter(|item| item.is_open()).count();
        if open > 0 {
            total += open;
            by_topic.push((topic, open));
        }
    }
    Some((total, by_topic))
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEMPLATE: &str = include_str!("../../../assets/base/pm/feedback.md.tmpl");

    fn project() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join(FEEDBACK_DIR)).unwrap();
        std::fs::create_dir_all(dir.path().join("project-management/tasks")).unwrap();
        std::fs::write(
            dir.path().join("project-management/tasks/TSK-001.md"),
            "---\nid: TSK-001\n---\n",
        )
        .unwrap();
        std::fs::write(dir.path().join("AGENTS.md"), "rules\n").unwrap();
        dir
    }

    /// Write an item from the shipped template, then apply `edit`.
    fn item(root: &Path, nnn: &str, edit: impl FnOnce(String) -> String) -> PathBuf {
        let uid = crate::ids::new_uid();
        let text = render(
            TEMPLATE,
            nnn,
            &uid,
            "a summary",
            "process",
            "chat",
            "2026-10-04",
        )
        .replace(
            "## Verbatim\n",
            "## Verbatim\n\n> track my input in order\n",
        );
        let path = root.join(FEEDBACK_DIR).join(format!("FB-{nnn}.md"));
        std::fs::write(&path, edit(text)).unwrap();
        path
    }

    fn messages(root: &Path) -> Vec<String> {
        lint(root)
            .errors
            .into_iter()
            .map(|finding| format!("{}: {}", finding.path, finding.message))
            .collect()
    }

    #[test]
    fn the_shipped_template_is_usable_and_a_broken_one_is_not() {
        check_template(TEMPLATE).unwrap();
        let broken = TEMPLATE.replace("status: received", "status: placed");
        assert!(check_template(&broken).unwrap_err().contains("status"));
        let missing = TEMPLATE.replace("{{TOPIC_YAML}}", "process");
        assert!(check_template(&missing)
            .unwrap_err()
            .contains("{{TOPIC_YAML}}"));
    }

    #[test]
    fn a_clean_set_passes_and_parses_every_field() {
        let dir = project();
        let root = dir.path();
        item(root, "001", |text| text);
        item(root, "002", |text| {
            text.replace("status: received ", "status: placed   ")
                .replace("placed_in: []", "placed_in: [TSK-001, AGENTS.md]")
        });
        assert!(messages(root).is_empty(), "{:?}", messages(root));
        let loaded = load(root);
        assert_eq!(loaded.items.len(), 2);
        let placed = &loaded.items[1];
        assert_eq!(placed.placed_in, ["TSK-001", "AGENTS.md"]);
        assert_eq!(placed.verbatim, "> track my input in order");
        assert!(placed.reading.is_empty(), "comments are not content");
    }

    #[test]
    fn each_structural_defect_fails_the_lint() {
        let dir = project();
        let root = dir.path();
        let first = item(root, "001", |text| text);
        let uid =
            crate::ids::entry::frontmatter_value(&std::fs::read_to_string(&first).unwrap(), "uid")
                .unwrap();
        // A duplicate uid.
        item(root, "002", |text| {
            let own = crate::ids::entry::frontmatter_value(&text, "uid").unwrap();
            text.replace(&own, &uid)
        });
        // An id that disagrees with its path.
        item(root, "003", |text| text.replace("id: FB-003", "id: FB-033"));
        // An unknown topic.
        item(root, "004", |text| {
            text.replace("topic: \"process\"", "topic: mood")
        });
        // Placed with no resolving placement.
        item(root, "005", |text| {
            text.replace("status: received ", "status: placed   ")
                .replace("placed_in: []", "placed_in: [TSK-404]")
        });
        // Closed with an empty Closure.
        item(root, "006", |text| {
            text.replace("status: received ", "status: closed   ")
        });
        // Declined without the operator's confirmation.
        item(root, "007", |text| {
            text.replace("status: received ", "status: declined ")
                .replace("## Closure\n", "## Closure\n\nnot now\n")
        });
        // An empty Verbatim.
        item(root, "008", |text| {
            text.replace("> track my input in order\n", "")
        });
        // Superseded by an item that does not exist.
        item(root, "009", |text| {
            text.replace("status: received ", "status: superseded")
                .replace("superseded_by: null", "superseded_by: FB-404")
        });
        let found = messages(root);
        for expected in [
            "FB-002.md: uid",
            "FB-003.md: id FB-033 disagrees with the file name FB-003.md",
            "FB-004.md: topic `mood`",
            "FB-005.md: placed_in entry TSK-404 does not resolve",
            "FB-006.md: a closed item has an empty Closure section",
            "FB-007.md: a declined item needs `confirmed_by: operator`",
            "FB-008.md: the Verbatim section is empty",
            "FB-009.md: superseded_by FB-404 does not resolve",
        ] {
            assert!(
                found.iter().any(|message| message.contains(expected)),
                "{expected} missing from {found:#?}"
            );
        }
        assert!(
            !found
                .iter()
                .any(|message| message.starts_with("project-management/feedback/FB-001.md")),
            "{found:#?}"
        );
    }

    #[test]
    fn placements_resolve_only_inside_the_repository() {
        let dir = project();
        let root = dir.path();
        assert!(placement_resolves(root, "TSK-001"));
        assert!(placement_resolves(root, "AGENTS.md#rules"));
        assert!(!placement_resolves(root, "TSK-002"));
        assert!(!placement_resolves(root, "EPC-001"));
        assert!(!placement_resolves(root, "FB-001"));
        assert!(!placement_resolves(root, "../AGENTS.md"));
        assert!(!placement_resolves(root, "/etc/hosts"));
        assert!(!placement_resolves(root, ""));
    }

    #[test]
    fn the_transition_table_is_the_only_way_through() {
        let dir = project();
        let root = dir.path();
        item(root, "001", |text| text);
        item(root, "002", |text| text);
        let change = |target: &str| StatusChange {
            target: target.to_string(),
            ..StatusChange::default()
        };
        let path = root.join(FEEDBACK_DIR).join("FB-001.md");
        let before = std::fs::read_to_string(&path).unwrap();
        // Off the table: received cannot close.
        let refused = set_status(root, "FB-001", &change("closed")).unwrap_err();
        assert!(refused.contains("received -> closed is not a feedback transition"));
        assert!(
            refused.contains("placed -> closed: --evidence"),
            "{refused}"
        );
        // On the table but missing what it needs, or not resolving.
        assert!(set_status(root, "FB-001", &change("placed"))
            .unwrap_err()
            .contains("--in"));
        let mut nowhere = change("placed");
        nowhere.placements = vec!["TSK-404".to_string()];
        assert!(set_status(root, "FB-001", &nowhere)
            .unwrap_err()
            .contains("does not resolve"));
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            before,
            "nothing written"
        );

        let mut placed = change("placed");
        placed.placements = vec!["TSK-001".to_string()];
        let outcome = set_status(root, "FB-001", &placed).unwrap();
        assert_eq!(
            (outcome.from.as_str(), outcome.to.as_str()),
            ("received", "placed")
        );
        let mut closed = change("closed");
        closed.evidence = Some("PR 90".to_string());
        set_status(root, "FB-001", &closed).unwrap();
        let mut superseded = change("superseded");
        superseded.by = Some("FB-001".to_string());
        assert!(set_status(root, "FB-001", &superseded)
            .unwrap_err()
            .contains("itself"));
        superseded.by = Some("FB-002".to_string());
        set_status(root, "FB-001", &superseded).unwrap();
        assert!(set_status(root, "FB-001", &change("received"))
            .unwrap_err()
            .contains("not a feedback transition"));

        let mut declined = change("declined");
        declined.reason = Some("out of scope".to_string());
        assert!(set_status(root, "FB-002", &declined)
            .unwrap_err()
            .contains("--confirmed-by operator"));
        declined.confirmed_by = Some("operator".to_string());
        set_status(root, "FB-002", &declined).unwrap();
        assert!(messages(root).is_empty(), "{:?}", messages(root));
        let items = load(root).items;
        assert_eq!(items[0].status, "superseded");
        assert_eq!(items[0].placed_in, ["TSK-001"]);
        assert_eq!(items[0].superseded_by.as_deref(), Some("FB-002"));
        assert!(items[0].closure.contains("closed by PR 90"));
        assert_eq!(items[1].confirmed_by.as_deref(), Some("operator"));
        assert!(items[1].closure.contains("out of scope"));
    }

    #[test]
    fn the_index_groups_open_first_and_a_stale_one_warns() {
        let dir = project();
        let root = dir.path();
        item(root, "001", |text| {
            text.replace("status: received ", "status: declined ")
                .replace("confirmed_by: null", "confirmed_by: operator")
        });
        item(root, "002", |text| text);
        item(root, "003", |text| {
            text.replace("topic: \"process\"", "topic: \"design\"")
        });
        let topics = topics(root).unwrap();
        let loaded = load(root);
        let groups = grouped(&loaded.items, &topics);
        let order: Vec<(String, Vec<String>)> = groups
            .into_iter()
            .map(|(topic, members)| (topic, members.iter().map(|i| i.id.clone()).collect()))
            .collect();
        assert_eq!(
            order,
            [
                (
                    "process".to_string(),
                    vec!["FB-002".to_string(), "FB-001".to_string()]
                ),
                ("design".to_string(), vec!["FB-003".to_string()]),
            ]
        );
        // Absent: nothing. Matching: nothing. Stale: one warning.
        assert!(lint(root).warnings.is_empty());
        std::fs::write(
            root.join(INDEX_PATH),
            render_index(&load(root).items, &topics),
        )
        .unwrap();
        assert!(lint(root).warnings.is_empty());
        item(root, "004", |text| text);
        let warnings = lint(root).warnings;
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0]
            .remedy
            .contains("codeflow feedback list --write"));
        assert_eq!(open_summary(root).unwrap().0, 3);
        let bare = tempfile::tempdir().unwrap();
        assert!(open_summary(bare.path()).is_none());
    }
}
