//! Derived lookup pages whose tables the binary generates from what it ships:
//! the skill catalog (the scaffold manifest's skills and each skill's own
//! description) and the policy reference (the policy key registry with live
//! defaults). A committed page carries the generated text between two marker
//! comments; `validate --portal` regenerates it and fails on any difference.
//! The policy reference also carries an authored table of the git hook
//! stages, whose set of stage names must equal the dispatcher's.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::hooks::policy_schema::{
    default_policy_value, lookup, render_value, schema, LEVEL_LEGEND,
};
use crate::scaffold::assets::AssetSource;
use crate::scaffold::manifest::{ScaffoldManifest, Tier};

/// The derivation name of the skill catalog.
pub const SKILL_CATALOG: &str = "skill-catalog";
/// The derivation name of the policy reference.
pub const POLICY_REFERENCE: &str = "policy-reference";
/// The heading of the authored hook stage section of the policy reference.
pub const HOOK_STAGES_HEADING: &str = "## Git hook stages";

/// What the binary supplies so a derived lookup can be regenerated: its
/// scaffold assets and the stage names its git hook dispatcher accepts.
///
/// The assets are the binary's own scaffold, never the validated project's
/// files. A release binary carries them embedded; a debug build of the binary
/// reads them from its own checkout's `assets/` tree, the same bytes a
/// release built from that checkout embeds, so the lookup pages of this
/// repository are checked against the scaffold they will ship with.
pub struct LookupInputs<'a> {
    pub assets: &'a dyn AssetSource,
    pub hook_stages: &'a [String],
}

/// A generated region and the number of table rows it holds.
#[derive(Debug, PartialEq, Eq)]
pub struct Generated {
    pub text: String,
    pub rows: usize,
}

fn begin_marker(derive: &str) -> String {
    format!(
        "<!-- codeflow-derived {derive} begin: generated by codeflow from the binary; do not edit between the markers. Regenerate with CODEFLOW_REGENERATE_LOOKUPS=1 cargo test -p codeflow-cli derived_lookup -->"
    )
}

fn end_marker(derive: &str) -> String {
    format!("<!-- codeflow-derived {derive} end -->")
}

/// The columns of the skill catalog table.
pub const SKILL_COLUMNS: [&str; 4] = ["Skill", "Use it for", "Installed at tiers", "Installed in"];
/// The columns of each policy reference table.
pub const POLICY_COLUMNS: [&str; 6] =
    ["Key", "Type", "Default", "Valid values", "Purpose", "Notes"];

/// A generated table. The portal adapter stacks it at phone width: it wraps a
/// table with these columns (`LOOKUP_COLUMNS` in the starter's
/// `page-classes.mjs`) in `.portal-lookup`, and the starter's stylesheet
/// labels every cell after the first with its column. A test pins both to
/// these column lists.
fn lookup_table(columns: &[&str], rows: &[String]) -> String {
    format!(
        "| {} |\n|{}\n{}",
        columns.join(" | "),
        "---|".repeat(columns.len()),
        rows.join("\n")
    )
}

/// A table cell: pipes escaped, line breaks folded to spaces.
fn cell(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The skill catalog page: every skill the scaffold manifest installs, with
/// the description from its own `SKILL.md` frontmatter, the tiers that
/// install it and the trees it lands in.
///
/// # Errors
///
/// Fails when the manifest or a skill's frontmatter cannot be read.
pub fn skill_catalog(assets: &dyn AssetSource) -> Result<Generated, String> {
    let manifest = ScaffoldManifest::load(assets).map_err(|error| error.to_string())?;
    // skill name -> (asset source, tiers, trees)
    let mut skills: BTreeMap<String, (String, Vec<Tier>, Vec<String>)> = BTreeMap::new();
    for entry in &manifest.entries {
        let Some(rest) = entry.dest.strip_suffix("/SKILL.md") else {
            continue;
        };
        let Some((tree, name)) = rest.rsplit_once('/') else {
            continue;
        };
        if !tree.ends_with("/skills") {
            continue;
        }
        let record = skills
            .entry(name.to_string())
            .or_insert_with(|| (entry.src.clone(), entry.tiers.clone(), Vec::new()));
        if record.0 != entry.src || record.1 != entry.tiers {
            return Err(format!(
                "skill {name} installs different sources or tiers in different trees"
            ));
        }
        record.2.push(format!("{tree}/"));
    }
    if skills.is_empty() {
        return Err("the scaffold manifest installs no skill".into());
    }
    let mut rows = Vec::new();
    for (name, (src, tiers, trees)) in &skills {
        let text = assets
            .read(&format!("base/{src}"))
            .and_then(|bytes| String::from_utf8(bytes).ok())
            .ok_or_else(|| format!("skill {name} source base/{src} is unreadable"))?;
        let description = skill_description(&text)
            .ok_or_else(|| format!("skill {name} has no frontmatter description"))?;
        let tiers: Vec<&str> = tiers.iter().map(|tier| tier.as_str()).collect();
        let trees: Vec<String> = trees.iter().map(|tree| format!("`{tree}`")).collect();
        rows.push(format!(
            "| `/{name}` | {} | {} | {} |",
            cell(&description),
            tiers.join(", "),
            trees.join(", ")
        ));
    }
    let count = rows.len();
    let text = format!(
        "{}\n\nThe skills CodeFlow installs, one row per skill. Each description is the skill's own, from its `SKILL.md`; the harness reads it to decide when the skill applies. The minimal tier installs no skill.\n\n{}\n\n{}\n",
        begin_marker(SKILL_CATALOG),
        lookup_table(&SKILL_COLUMNS, &rows),
        end_marker(SKILL_CATALOG)
    );
    Ok(Generated { text, rows: count })
}

/// The `description` of a `SKILL.md` frontmatter block.
fn skill_description(text: &str) -> Option<String> {
    let body = text.strip_prefix("---\n")?;
    let (frontmatter, _) = body.split_once("\n---")?;
    let value: serde_yaml::Value = serde_yaml::from_str(frontmatter).ok()?;
    value.get("description")?.as_str().map(str::to_string)
}

/// The generated region of the policy reference: every key the policy file
/// accepts, grouped as `codeflow policy explain` groups them, with defaults
/// taken live from the built-in policy.
#[must_use]
pub fn policy_reference() -> Generated {
    let defaults = default_policy_value();
    let mut sections: Vec<(&str, Vec<String>)> = Vec::new();
    for spec in schema() {
        let group = match spec.path.split_once('.') {
            Some(("git", _)) => "Git keys",
            Some(("security", _)) => "Security keys",
            _ => "Top-level keys",
        };
        if sections.last().is_none_or(|(name, _)| *name != group) {
            sections.push((group, Vec::new()));
        }
        let default = lookup(&defaults, spec.path).map_or_else(String::new, render_value);
        let row = format!(
            "| `{}` | {} | `{}` | {} | {} | {} |",
            spec.path,
            spec.kind.type_name(),
            cell(&default),
            cell(spec.valid),
            cell(spec.purpose),
            cell(spec.notes)
        );
        if let Some((_, rows)) = sections.last_mut() {
            rows.push(row);
        }
    }
    let mut text = format!(
        "{}\n\nEvery key `.codeflow/policy.json` accepts, with its type, built-in default and valid values. A missing file or key means the default applies; `codeflow policy show` prints the values in effect for a repository.\n\nLevel keys accept `off`, `warn`, `allow` or `block`: {}\n",
        begin_marker(POLICY_REFERENCE),
        cell(LEVEL_LEGEND)
    );
    for (group, rows) in &sections {
        write!(
            text,
            "\n## {group}\n\n{}\n",
            lookup_table(&POLICY_COLUMNS, rows)
        )
        .expect("writing to a String cannot fail");
    }
    writeln!(text, "\n{}", end_marker(POLICY_REFERENCE)).expect("writing to a String cannot fail");
    Generated {
        text,
        rows: schema().len(),
    }
}

/// The stage names in the first column of the table under
/// [`HOOK_STAGES_HEADING`], backticks removed, or `None` when the section or
/// its table is missing.
#[must_use]
pub fn hook_stage_names(page: &str) -> Option<Vec<String>> {
    let (_, section) = page.split_once(&format!("\n{HOOK_STAGES_HEADING}\n"))?;
    let section = section.split("\n## ").next().unwrap_or(section);
    let rows: Vec<&str> = section
        .lines()
        .filter(|line| line.starts_with('|'))
        .collect();
    if rows.len() < 3 {
        return None;
    }
    Some(
        rows[2..]
            .iter()
            .filter_map(|row| row.split('|').nth(1))
            .map(|name| name.trim().trim_matches('`').to_string())
            .collect(),
    )
}

/// The body a committed lookup page must start with after its title: the
/// title line, a blank line, then the generated region.
#[must_use]
pub fn page_with_title(title: &str, generated: &Generated) -> String {
    format!("# {title}\n\n{}", generated.text)
}

/// The title each generated page carries.
#[must_use]
pub fn title_of(derive: &str) -> Option<&'static str> {
    match derive {
        SKILL_CATALOG => Some("Skills"),
        POLICY_REFERENCE => Some("Policy and hook reference"),
        _ => None,
    }
}

/// Regenerate a lookup page and compare it with the committed source: the
/// page starts with its title and generated region; the skill catalog ends
/// there, and the policy reference continues with the authored stage table,
/// whose names must be exactly the dispatcher's. Returns the rows the page's
/// tables must hold, or the reason it does not match.
///
/// # Errors
///
/// Names the first difference between the committed page and its derivation.
pub fn verify_lookup_page(
    derive: &str,
    source: &str,
    inputs: &LookupInputs<'_>,
) -> Result<usize, String> {
    let title = title_of(derive).ok_or_else(|| format!("{derive} is not a generated lookup"))?;
    let generated = match derive {
        SKILL_CATALOG => skill_catalog(inputs.assets)?,
        _ => policy_reference(),
    };
    let expected = page_with_title(title, &generated);
    let Some(rest) = source.strip_prefix(&expected) else {
        return Err(format!(
            "the committed page differs from its {derive} derivation; regenerate it"
        ));
    };
    if derive == SKILL_CATALOG {
        return if rest.trim().is_empty() {
            Ok(generated.rows)
        } else {
            Err("the skill catalog carries text after its generated region".into())
        };
    }
    let mut on_page =
        hook_stage_names(rest).ok_or("the policy reference has no git hook stage table")?;
    let mut dispatcher = inputs.hook_stages.to_vec();
    on_page.sort();
    dispatcher.sort();
    if on_page != dispatcher {
        return Err(format!(
            "the git hook stage table names {} but the dispatcher accepts {}",
            on_page.join(", "),
            dispatcher.join(", ")
        ));
    }
    Ok(generated.rows + dispatcher.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scaffold::assets::DirSource;
    use std::path::Path;

    fn assets() -> DirSource {
        DirSource::new(Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets"))
    }

    fn stages() -> Vec<String> {
        [
            "pre-commit",
            "commit-msg",
            "pre-merge-commit",
            "reference-transaction",
            "pre-push",
        ]
        .map(String::from)
        .to_vec()
    }

    #[test]
    fn the_skill_catalog_lists_every_installed_skill_once() {
        let catalog = skill_catalog(&assets()).unwrap();
        assert!(catalog.rows >= 1);
        assert!(catalog.text.contains("| `/cf-ship` | Land finished work"));
        assert!(!catalog.text.contains('\u{2014}'));
        assert_eq!(
            catalog.text.matches("\n| `/cf-").count(),
            catalog.rows,
            "{}",
            catalog.text
        );
    }

    #[test]
    fn the_policy_reference_lists_every_key_with_its_default() {
        let reference = policy_reference();
        assert_eq!(reference.rows, schema().len());
        assert!(reference
            .text
            .contains("| `git.protected_branches` | string list | `[\"main\",\"master\"]` |"));
        assert!(reference.text.contains("off \\| warn \\| allow \\| block"));
        assert!(!reference.text.contains('\u{2014}'));
    }

    #[test]
    fn the_starter_stacks_each_lookup_under_its_generated_columns() {
        let starter =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets/docs-portal/starter");
        let css = std::fs::read_to_string(starter.join("src/styles/portal.css")).unwrap();
        let classes = std::fs::read_to_string(starter.join("scripts/page-classes.mjs")).unwrap();
        let catalog = skill_catalog(&assets()).unwrap().text;
        let reference = policy_reference().text;
        for (derive, columns, text) in [
            (SKILL_CATALOG, &SKILL_COLUMNS[..], &catalog),
            (POLICY_REFERENCE, &POLICY_COLUMNS[..], &reference),
        ] {
            // The generator writes the header from the column list.
            assert!(
                text.contains(&format!("\n| {} |\n", columns.join(" | "))),
                "{text}"
            );
            // The adapter wraps a table with exactly these columns.
            let quoted: Vec<String> = columns
                .iter()
                .map(|column| format!("\"{column}\""))
                .collect();
            let entry = format!("\"{derive}\": [{}]", quoted.join(", "));
            assert!(classes.contains(&entry), "page-classes.mjs lacks {entry}");
            // The stylesheet labels every column after the first, and no more.
            for (index, column) in columns.iter().enumerate().skip(1) {
                let rule = format!(
                    ".portal-lookup[data-cf-lookup=\"{derive}\"] td:nth-child({})::before {{ content: \"{column}\"; }}",
                    index + 1
                );
                assert!(css.contains(&rule), "portal.css lacks {rule}");
            }
            let extra = format!(
                ".portal-lookup[data-cf-lookup=\"{derive}\"] td:nth-child({})::before",
                columns.len() + 1
            );
            assert!(
                !css.contains(&extra),
                "portal.css labels a column {derive} does not have"
            );
        }
    }

    #[test]
    fn a_page_is_held_to_its_derivation_and_the_dispatcher() {
        let dir = assets();
        let stage_names = stages();
        let inputs = LookupInputs {
            assets: &dir,
            hook_stages: &stage_names,
        };
        let stage_table = "\n## Git hook stages\n\nWritten here.\n\n| Stage | What it checks |\n|---|---|\n| `pre-commit` | a |\n| `commit-msg` | b |\n| `pre-merge-commit` | c |\n| `reference-transaction` | d |\n| `pre-push` | e |\n";
        let reference = page_with_title("Policy and hook reference", &policy_reference());
        let page = format!("{reference}{stage_table}");
        assert_eq!(
            verify_lookup_page(POLICY_REFERENCE, &page, &inputs),
            Ok(schema().len() + 5)
        );
        // A stage missing from, or added to, the authored table is refused.
        let missing = page.replace("| `pre-push` | e |\n", "");
        assert!(verify_lookup_page(POLICY_REFERENCE, &missing, &inputs)
            .unwrap_err()
            .contains("the dispatcher accepts"));
        let extra = format!("{page}| `post-merge` | f |\n");
        assert!(verify_lookup_page(POLICY_REFERENCE, &extra, &inputs).is_err());
        // An edit inside the generated region is refused.
        let edited = page.replacen("Branches every", "Branches some", 1);
        assert!(verify_lookup_page(POLICY_REFERENCE, &edited, &inputs)
            .unwrap_err()
            .contains("regenerate it"));
        let catalog = page_with_title("Skills", &skill_catalog(&dir).unwrap());
        assert!(verify_lookup_page(SKILL_CATALOG, &catalog, &inputs).is_ok());
        assert!(
            verify_lookup_page(SKILL_CATALOG, &format!("{catalog}\nMore.\n"), &inputs).is_err()
        );
    }
}
