id = "TSK-003-004"
uid = "cd175a6d-ea07-4638-b696-afb216563c88"
kind = "TSK"
title = "verify and ship integrated change"
issuer = "seed"
created = "2026-09-27T13:28:44Z"
target = "integration/EPC-005-presentation-system"
introduced = "f89f4a96e9545bd95d8c4d0dafc14f4a301f6599@integration/EPC-005-presentation-system"
landed = "f89f4a96e9545bd95d8c4d0dafc14f4a301f6599"
mapped = []
mapped_by = "none"
