id = "TSK-006"
uid = "0af2d9e1-2588-4ddc-a3be-024ee1418af6"
kind = "TSK"
title = "research and prototype the presentation experience"
issuer = "seed"
created = "2026-09-27T13:28:46Z"
target = "integration/EPC-005-presentation-system"
introduced = "d7518ca12dcc84bb918dd8713d49d67f5e172f80@integration/EPC-005-presentation-system"
landed = "d7518ca12dcc84bb918dd8713d49d67f5e172f80"
mapped = []
mapped_by = "none"
