id = "TSK-200"
uid = "c8e63c8a-0fa8-4e06-a533-3c273c428aa5"
kind = "TSK"
title = "Release 3.0.0 without Windows"
issuer = "26560960+sathyassn@users.noreply.github.com"
created = "2026-10-01T22:11:02Z"
target = "main"
introduced = "none"
landed = "none"
mapped = []
mapped_by = "none"
