id = "TSK-235"
uid = "36b230b0-803f-4caa-86ee-cc77fddbbd72"
kind = "TSK"
title = "Guidance for working while something is uncertain"
issuer = "26560960+sathyassn@users.noreply.github.com"
created = "2026-10-04T16:32:19Z"
target = "main"
introduced = "none"
landed = "none"
mapped = []
mapped_by = "none"
