#!/usr/bin/env bash
# Purpose:   Enforce git-workflow skill PR format AND block AI attribution
# Location:  .claude/hooks/codeflow/pre-tool-use/cf-pre-tool-use-gh-pr.sh
# Hook Type: PreToolUse
# Matcher:   Bash
# Skill:     git-workflow
# Operation: create-pull-request
#
# Configuration: Reads from enforcement-policy.json (git_format section)
#                Falls back to defaults if config unavailable
#
# Exit codes:
#   - 0: Command allowed
#   - 2: Command blocked (validation failed)

set -euo pipefail

# ============================================
# CONFIGURATION (Config-driven)
# ============================================

# Get repo root using git (most robust) or fallback to relative path
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || { cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd; })"
CONFIG_FILE="$REPO_ROOT/.codeflow/config/enforcement/enforcement-policy.json"
LIB_DIR="$REPO_ROOT/.codeflow/scripts/security/lib"

# Source security library for logging
if [[ -f "$LIB_DIR/security-lib.sh" ]]; then
    export REPO_ROOT LIB_DIR
    # shellcheck source=/dev/null
    source "$LIB_DIR/security-lib.sh"
fi

# Default fallbacks (used if config unavailable)
DEFAULT_VALID_TYPES="feat|fix|bugfix|hotfix|docs|refactor|test|chore|style|perf|build|ci|revert|merge|plan|refine"
DEFAULT_AI_PATTERN="Claude|ChatGPT|Copilot|Gemini|Cursor|Codeium|Tabnine|CodeWhisperer|Anthropic|OpenAI|Generated with|Generated by|AI-generated|AI generated|Co-Authored-By:.*(AI|Claude|ChatGPT|Copilot)|🤖|🔮"
DEFAULT_MAX_TITLE_LENGTH=50

# Load from config or use defaults
if [[ -f "$CONFIG_FILE" ]] && command -v jq &>/dev/null; then
    # Load commit types as pipe-separated string
    TYPES_ARRAY=$(jq -r '.git_format.commit_types // empty | join("|")' "$CONFIG_FILE" 2>/dev/null)
    VALID_TYPES="${TYPES_ARRAY:-$DEFAULT_VALID_TYPES}"

    # Load AI patterns as pipe-separated regex
    AI_ARRAY=$(jq -r '.git_format.ai_attribution_patterns // empty | join("|")' "$CONFIG_FILE" 2>/dev/null)
    AI_PATTERN="${AI_ARRAY:-$DEFAULT_AI_PATTERN}"

    # Load max title length
    MAX_LEN=$(jq -r '.git_format.subject.max_length // empty' "$CONFIG_FILE" 2>/dev/null)
    MAX_TITLE_LENGTH="${MAX_LEN:-$DEFAULT_MAX_TITLE_LENGTH}"

    # Load required sections into array (bash 3.2 compatible)
    REQUIRED_SECTIONS=()
    while IFS= read -r section; do
        [[ -n "$section" ]] && REQUIRED_SECTIONS+=("$section")
    done < <(jq -r '.git_format.pr.required_sections // empty | .[]' "$CONFIG_FILE" 2>/dev/null)
    [[ ${#REQUIRED_SECTIONS[@]} -eq 0 ]] && REQUIRED_SECTIONS=("## Summary" "## Testing")

    # Load require_body_flag
    REQUIRE_BODY=$(jq -r '.git_format.pr.require_body_flag // "true"' "$CONFIG_FILE" 2>/dev/null)
else
    # Fallback to defaults
    VALID_TYPES="$DEFAULT_VALID_TYPES"
    AI_PATTERN="$DEFAULT_AI_PATTERN"
    MAX_TITLE_LENGTH="$DEFAULT_MAX_TITLE_LENGTH"
    REQUIRED_SECTIONS=("## Summary" "## Testing")
    REQUIRE_BODY="true"
fi

# ============================================
# EARLY EXIT FOR NON-BASH TOOLS
# ============================================

TOOL_NAME="${TOOL_NAME:-}"
if [[ "$TOOL_NAME" != "Bash" ]]; then
    exit 0
fi

# ============================================
# PARSE INPUT
# ============================================

TOOL_INPUT="${TOOL_INPUT:-}"
if [[ -z "$TOOL_INPUT" ]]; then
    exit 0
fi

# Extract command from JSON
COMMAND=""
if command -v jq &>/dev/null; then
    COMMAND=$(echo "$TOOL_INPUT" | jq -r '.command // empty')
else
    # Fallback: extract command value
    COMMAND=$(echo "$TOOL_INPUT" | grep -o '"command":"[^"]*"' | sed 's/"command":"//;s/"$//' || echo "")
fi

# Exit early if no command extracted
[[ -z "$COMMAND" ]] && exit 0

# ============================================
# DETECT PR CREATION
# ============================================

# Only process gh pr create commands
if ! echo "$COMMAND" | grep -qE "gh[[:space:]]+pr[[:space:]]+create"; then
    exit 0
fi

# ============================================
# HELPER: Print skill direction block
# ============================================
print_skill_block() {
    cat >&2 <<'EOF'
MUST: Skill('cf-git-workflow', args='create-pull-request') FIRST
EOF
}

# ============================================
# CHECK 1: BLOCK INTERACTIVE MODE (no --body)
# ============================================

if [[ "$REQUIRE_BODY" == "true" ]] && ! echo "$COMMAND" | grep -qE "\-\-body|\-b[[:space:]]"; then
    if declare -f log_security_event &>/dev/null; then
        log_security_event "blocked" "pr_no_body" "Bash" "$COMMAND" "Interactive PR mode"
    fi
    cat >&2 <<'EOF'
BLOCKED: Interactive PR mode not allowed (requires --body with sections)
EOF
    print_skill_block
    exit 2
fi

# ============================================
# CHECK 2: AI ATTRIBUTION (BLOCK)
# ============================================

if echo "$COMMAND" | grep -qEi "$AI_PATTERN"; then
    if declare -f log_security_event &>/dev/null; then
        log_security_event "blocked" "pr_ai_attribution" "Bash" "$COMMAND" "AI attribution detected"
    fi
    cat >&2 <<'EOF'
BLOCKED: AI attribution forbidden in PR titles/descriptions
EOF
    print_skill_block
    exit 2
fi

# ============================================
# CHECK 3: REQUIRED SECTIONS (from config)
# ============================================

for section in "${REQUIRED_SECTIONS[@]}"; do
    if ! echo "$COMMAND" | grep -qF "$section"; then
        if declare -f log_security_event &>/dev/null; then
            log_security_event "blocked" "pr_missing_section" "Bash" "$COMMAND" "Missing: $section"
        fi
        cat >&2 <<EOF
BLOCKED: Missing required section: $section
EOF
        print_skill_block
        exit 2
    fi
done

# ============================================
# CHECK 4: TITLE FORMAT (conventional commit)
# ============================================

# Extract title using robust separate patterns
TITLE=""

# Pattern 1: --title "double quoted"
if [[ "$COMMAND" =~ --title[[:space:]]+\"([^\"]+)\" ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 2: --title 'single quoted'
elif [[ "$COMMAND" =~ --title[[:space:]]+\'([^\']+)\' ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 3: -t "double quoted"
elif [[ "$COMMAND" =~ -t[[:space:]]+\"([^\"]+)\" ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 4: -t 'single quoted'
elif [[ "$COMMAND" =~ -t[[:space:]]+\'([^\']+)\' ]]; then
    TITLE="${BASH_REMATCH[1]}"
fi

# Only validate if we extracted a title
if [[ -n "$TITLE" ]]; then
    # Check title length (from config)
    if [[ ${#TITLE} -gt $MAX_TITLE_LENGTH ]]; then
        if declare -f log_security_event &>/dev/null; then
            log_security_event "blocked" "pr_title_length" "Bash" "$TITLE" "Exceeds $MAX_TITLE_LENGTH chars"
        fi
        cat >&2 <<EOF
BLOCKED: PR title exceeds $MAX_TITLE_LENGTH chars (${#TITLE}): "${TITLE}"
EOF
        print_skill_block
        exit 2
    fi

    # Check title has conventional commit prefix with colon-space
    if ! echo "$TITLE" | grep -qE "^(${VALID_TYPES}): "; then
        if declare -f log_security_event &>/dev/null; then
            log_security_event "blocked" "pr_title_format" "Bash" "$TITLE" "Invalid format"
        fi
        cat >&2 <<EOF
BLOCKED: Invalid PR title format (need type: desc): "${TITLE}"
EOF
        print_skill_block
        exit 2
    fi
fi

# ============================================
# ALL CHECKS PASSED
# ============================================

exit 0
