#!/usr/bin/env bash
# Purpose:   Enforce git-workflow skill PR format, block AI attribution, AND
#            block gh pr merge on protected branches
# Location:  .claude/hooks/codeflow/pre-tool-use/cf-pre-tool-use-gh-pr.sh
# Hook Type: PreToolUse
# Matcher:   Bash
# Teammate:  cf-git-operations
# Operation: create-pull-request
#
# Configuration: Reads from enforcement-policy.json (git_format + merge_protection)
#                Falls back to defaults if config unavailable
#
# Exit codes:
#   - 0: Command allowed
#   - 2: Command blocked (validation failed)

set -euo pipefail


# =============================================================================
# HOOK INPUT PARSING (Claude Code sends JSON on stdin)
# =============================================================================

# Read hook data from stdin (Claude Code protocol) or env vars (test fallback)
if [[ ! -t 0 ]]; then
    _HOOK_STDIN=$(cat)
    if [[ -n "$_HOOK_STDIN" ]] && command -v jq &>/dev/null; then
        _tn=$(echo "$_HOOK_STDIN" | jq -r '.tool_name // empty' 2>/dev/null)
        [[ -n "$_tn" ]] && TOOL_NAME="$_tn"
        _ti=$(echo "$_HOOK_STDIN" | jq -c '.tool_input // empty' 2>/dev/null)
        [[ -n "$_ti" ]] && [[ "$_ti" != "null" ]] && TOOL_INPUT="$_ti"
    fi
fi

# ============================================
# CONFIGURATION (Config-driven)
# ============================================

# Get repo root using git (most robust) or fallback to relative path
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || { cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd; })}"
CONFIG_FILE="$REPO_ROOT/.codeflow/config/enforcement/enforcement-policy.json"
LIB_DIR="$REPO_ROOT/.codeflow/scripts/security/lib"

# Source security library for logging
if [[ -f "$LIB_DIR/security-lib.sh" ]]; then
    export REPO_ROOT LIB_DIR
    # shellcheck source=/dev/null
    source "$LIB_DIR/security-lib.sh"
fi

# Default fallbacks (used if config unavailable)
DEFAULT_VALID_TYPES="feat|fix|bugfix|hotfix|docs|refactor|test|chore|style|perf|build|ci|revert|merge|plan|refine"
DEFAULT_AI_PATTERN="Claude|ChatGPT|Copilot|Gemini|Cursor|Codeium|Tabnine|CodeWhisperer|Anthropic|OpenAI|Generated with|Generated by|AI-generated|AI generated|Co-Authored-By:.*(AI|Claude|ChatGPT|Copilot)|🤖|🔮"
DEFAULT_MAX_TITLE_LENGTH=50

# Load from config or use defaults
if [[ -f "$CONFIG_FILE" ]] && command -v jq &>/dev/null; then
    # Load commit types as pipe-separated string
    TYPES_ARRAY=$(jq -r '.git_format.commit_types // empty | join("|")' "$CONFIG_FILE" 2>/dev/null)
    VALID_TYPES="${TYPES_ARRAY:-$DEFAULT_VALID_TYPES}"

    # Load AI patterns as pipe-separated regex
    AI_ARRAY=$(jq -r '.git_format.ai_attribution_patterns // empty | join("|")' "$CONFIG_FILE" 2>/dev/null)
    AI_PATTERN="${AI_ARRAY:-$DEFAULT_AI_PATTERN}"

    # Load max title length
    MAX_LEN=$(jq -r '.git_format.subject.max_length // empty' "$CONFIG_FILE" 2>/dev/null)
    MAX_TITLE_LENGTH="${MAX_LEN:-$DEFAULT_MAX_TITLE_LENGTH}"

    # Load required sections into array (bash 3.2 compatible)
    REQUIRED_SECTIONS=()
    while IFS= read -r section; do
        [[ -n "$section" ]] && REQUIRED_SECTIONS+=("$section")
    done < <(jq -r '.git_format.pr.required_sections // empty | .[]' "$CONFIG_FILE" 2>/dev/null)
    [[ ${#REQUIRED_SECTIONS[@]} -eq 0 ]] && REQUIRED_SECTIONS=("## Summary" "## Testing")

    # Load require_body_flag
    REQUIRE_BODY=$(jq -r '.git_format.pr.require_body_flag // "true"' "$CONFIG_FILE" 2>/dev/null)
else
    # Fallback to defaults
    VALID_TYPES="$DEFAULT_VALID_TYPES"
    AI_PATTERN="$DEFAULT_AI_PATTERN"
    MAX_TITLE_LENGTH="$DEFAULT_MAX_TITLE_LENGTH"
    REQUIRED_SECTIONS=("## Summary" "## Testing")
    REQUIRE_BODY="true"
fi

# ============================================
# EARLY EXIT FOR NON-BASH TOOLS
# ============================================

TOOL_NAME="${TOOL_NAME:-}"
if [[ "$TOOL_NAME" != "Bash" ]]; then
    exit 0
fi

# ============================================
# PARSE INPUT
# ============================================

TOOL_INPUT="${TOOL_INPUT:-}"
if [[ -z "$TOOL_INPUT" ]]; then
    exit 0
fi

# Extract command from JSON
COMMAND=""
if command -v jq &>/dev/null; then
    COMMAND=$(echo "$TOOL_INPUT" | jq -r '.command // empty')
else
    # Fallback: extract command value
    COMMAND=$(echo "$TOOL_INPUT" | grep -o '"command":"[^"]*"' | sed 's/"command":"//;s/"$//' || echo "")
fi

# Exit early if no command extracted
[[ -z "$COMMAND" ]] && exit 0

# ============================================
# DETECT PR MERGE (merge protection)
# ============================================

if echo "$COMMAND" | grep -qE "gh[[:space:]]+pr[[:space:]]+merge"; then

    # Load merge protection config
    MERGE_PROTECTED_BRANCHES=()
    if [[ -f "$CONFIG_FILE" ]] && command -v jq &>/dev/null; then
        while IFS= read -r branch; do
            [[ -n "$branch" ]] && MERGE_PROTECTED_BRANCHES+=("$branch")
        done < <(jq -r '.merge_protection.protected_branches[]? // empty' "$CONFIG_FILE" 2>/dev/null)
    fi

    # Fallback to defaults if config unavailable
    if [[ ${#MERGE_PROTECTED_BRANCHES[@]} -eq 0 ]]; then
        MERGE_PROTECTED_BRANCHES=("main" "master" "release/*" "production")
    fi

    # Extract PR number from command (first positional arg after 'gh pr merge')
    PR_NUMBER=""
    if [[ "$COMMAND" =~ gh[[:space:]]+pr[[:space:]]+merge[[:space:]]+([0-9]+) ]]; then
        PR_NUMBER="${BASH_REMATCH[1]}"
    fi

    if [[ -z "$PR_NUMBER" ]]; then
        # No PR number found — cannot determine target branch, allow through
        exit 0
    fi

    # Resolve target branch via gh pr view
    TARGET_BRANCH=""
    TARGET_BRANCH=$(gh pr view "$PR_NUMBER" --json baseRefName --jq '.baseRefName' 2>/dev/null || true)

    if [[ -z "$TARGET_BRANCH" ]]; then
        # Cannot resolve target branch (API failure, PR not found) — allow through
        # The gh pr merge command itself will fail with a proper error
        exit 0
    fi

    # Check if target branch matches any protected branch pattern
    for protected in "${MERGE_PROTECTED_BRANCHES[@]}"; do
        matched=false

        # Exact match
        if [[ "$TARGET_BRANCH" == "$protected" ]]; then
            matched=true
        fi

        # Glob/fnmatch match (e.g., release/*)
        if [[ "$matched" == "false" ]] && [[ "$protected" == *"*"* ]]; then
            # shellcheck disable=SC2053
            if [[ "$TARGET_BRANCH" == $protected ]]; then
                matched=true
            fi
        fi

        if [[ "$matched" == "true" ]]; then
            if declare -f log_security_event &>/dev/null; then
                log_security_event "blocked" "pr_merge_protected" "Bash" "$COMMAND" "Protected branch: $TARGET_BRANCH"
            fi
            cat >&2 <<EOF
BLOCKED: Cannot merge PR #${PR_NUMBER} into protected branch '${TARGET_BRANCH}'.
Protected branches require manual merge via GitHub UI or admin override.
Matched protection pattern: ${protected}

MUST: Do not attempt to merge into protected branches via CLI.
EOF
            exit 2
        fi
    done

    # Target branch is not protected — allow merge
    exit 0
fi

# ============================================
# DETECT PR CREATION
# ============================================

# Only process gh pr create commands
if ! echo "$COMMAND" | grep -qE "gh[[:space:]]+pr[[:space:]]+create"; then
    exit 0
fi

# ============================================
# HELPER: Print teammate direction block
# ============================================
print_skill_block() {
    cat >&2 <<'EOF'
MUST: Delegate to cf-git-operations teammate for PR creation: SendMessage(recipient="cf-git-operations", content="create-pull-request")
EOF
}

# ============================================
# EXTRACT BODY CONTENT (inline or from file)
# ============================================

BODY_CONTENT=""
HAS_BODY_FLAG=false

# Check for --body-file or -F (file-based body)
BODY_FILE_PATH=""
if [[ "$COMMAND" =~ --body-file[[:space:]]+\"([^\"]+)\" ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ --body-file[[:space:]]+\'([^\']+)\' ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ --body-file[[:space:]]+([^[:space:]]+) ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ -F[[:space:]]+\"([^\"]+)\" ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ -F[[:space:]]+\'([^\']+)\' ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ -F[[:space:]]+([^[:space:]]+) ]]; then
    BODY_FILE_PATH="${BASH_REMATCH[1]}"
fi

if [[ -n "$BODY_FILE_PATH" ]]; then
    HAS_BODY_FLAG=true
    if [[ -f "$BODY_FILE_PATH" ]]; then
        BODY_CONTENT=$(cat "$BODY_FILE_PATH" 2>/dev/null || true)
    fi
    # If file doesn't exist or can't be read, allow through (don't block on missing file)
fi

# Check for --body or -b (inline body)
if echo "$COMMAND" | grep -qE "\-\-body|\-b[[:space:]]"; then
    HAS_BODY_FLAG=true
    # Extract inline body for checks
    if [[ "$COMMAND" =~ --body[[:space:]]+\"([^\"]+)\" ]]; then
        BODY_CONTENT="${BASH_REMATCH[1]}"
    elif [[ "$COMMAND" =~ --body[[:space:]]+\'\(([^\']+)\)\' ]]; then
        BODY_CONTENT="${BASH_REMATCH[1]}"
    elif [[ "$COMMAND" =~ -b[[:space:]]+\"([^\"]+)\" ]]; then
        BODY_CONTENT="${BASH_REMATCH[1]}"
    fi
fi

# ============================================
# CHECK 1: BLOCK INTERACTIVE MODE (no --body)
# ============================================

if [[ "$REQUIRE_BODY" == "true" ]] && [[ "$HAS_BODY_FLAG" == "false" ]]; then
    if declare -f log_security_event &>/dev/null; then
        log_security_event "blocked" "pr_no_body" "Bash" "$COMMAND" "Interactive PR mode"
    fi
    cat >&2 <<'EOF'
BLOCKED: Interactive PR mode not allowed (requires --body with sections)
EOF
    print_skill_block
    exit 2
fi

# ============================================
# CHECK 2: AI ATTRIBUTION (BLOCK)
# ============================================

# Build check string from title + body content only (not raw command with file paths)
AI_CHECK_STRING=""

# Extract title value for AI check
if [[ "$COMMAND" =~ --title[[:space:]]+\"([^\"]+)\" ]]; then
    AI_CHECK_STRING="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ --title[[:space:]]+\'([^\']+)\' ]]; then
    AI_CHECK_STRING="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ -t[[:space:]]+\"([^\"]+)\" ]]; then
    AI_CHECK_STRING="${BASH_REMATCH[1]}"
elif [[ "$COMMAND" =~ -t[[:space:]]+\'([^\']+)\' ]]; then
    AI_CHECK_STRING="${BASH_REMATCH[1]}"
fi

# Append body content
if [[ -n "$BODY_CONTENT" ]]; then
    AI_CHECK_STRING="${AI_CHECK_STRING} ${BODY_CONTENT}"
fi

if [[ -n "$AI_CHECK_STRING" ]] && echo "$AI_CHECK_STRING" | grep -qEi "$AI_PATTERN"; then
    if declare -f log_security_event &>/dev/null; then
        log_security_event "blocked" "pr_ai_attribution" "Bash" "$COMMAND" "AI attribution detected"
    fi
    cat >&2 <<'EOF'
BLOCKED: AI attribution forbidden in PR titles/descriptions
EOF
    print_skill_block
    exit 2
fi

# ============================================
# CHECK 3: REQUIRED SECTIONS (from config)
# ============================================

# Check body content (inline or from file) for required sections
CHECK_CONTENT="$BODY_CONTENT"
# Fallback: if no body content extracted yet and no body-file was used, check full command
if [[ -z "$CHECK_CONTENT" ]] && [[ -z "$BODY_FILE_PATH" ]]; then
    CHECK_CONTENT="$COMMAND"
fi

# Only check sections if we have content to check (skip if body-file was unreadable)
if [[ -n "$CHECK_CONTENT" ]]; then
    for section in "${REQUIRED_SECTIONS[@]}"; do
        if ! echo "$CHECK_CONTENT" | grep -qF "$section"; then
            if declare -f log_security_event &>/dev/null; then
                log_security_event "blocked" "pr_missing_section" "Bash" "$COMMAND" "Missing: $section"
            fi
            cat >&2 <<EOF
BLOCKED: Missing required section: $section
EOF
            print_skill_block
            exit 2
        fi
    done
fi

# ============================================
# CHECK 4: TITLE FORMAT (conventional commit)
# ============================================

# Extract title using robust separate patterns
TITLE=""

# Pattern 1: --title "double quoted"
if [[ "$COMMAND" =~ --title[[:space:]]+\"([^\"]+)\" ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 2: --title 'single quoted'
elif [[ "$COMMAND" =~ --title[[:space:]]+\'([^\']+)\' ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 3: -t "double quoted"
elif [[ "$COMMAND" =~ -t[[:space:]]+\"([^\"]+)\" ]]; then
    TITLE="${BASH_REMATCH[1]}"
# Pattern 4: -t 'single quoted'
elif [[ "$COMMAND" =~ -t[[:space:]]+\'([^\']+)\' ]]; then
    TITLE="${BASH_REMATCH[1]}"
fi

# Only validate if we extracted a title
if [[ -n "$TITLE" ]]; then
    # Check title length (from config)
    if [[ ${#TITLE} -gt $MAX_TITLE_LENGTH ]]; then
        if declare -f log_security_event &>/dev/null; then
            log_security_event "blocked" "pr_title_length" "Bash" "$TITLE" "Exceeds $MAX_TITLE_LENGTH chars"
        fi
        cat >&2 <<EOF
BLOCKED: PR title exceeds $MAX_TITLE_LENGTH chars (${#TITLE}): "${TITLE}"
EOF
        print_skill_block
        exit 2
    fi

    # Check title has conventional commit prefix with optional scope and colon-space
    if ! echo "$TITLE" | grep -qE "^(${VALID_TYPES})(\([a-z0-9-]+\))?: "; then
        if declare -f log_security_event &>/dev/null; then
            log_security_event "blocked" "pr_title_format" "Bash" "$TITLE" "Invalid format"
        fi
        cat >&2 <<EOF
BLOCKED: Invalid PR title format (need type: desc): "${TITLE}"
EOF
        print_skill_block
        exit 2
    fi
fi

# ============================================
# ALL CHECKS PASSED
# ============================================

exit 0
