package ledger

import (
	"encoding/json"
	"fmt"
	"time"
)

// Event represents a single JSONL ledger event with canonical fields.
type Event struct {
	// EventType is the canonical event type (e.g., "session_start", "task_created").
	EventType string `json:"event"`

	// Timestamp is the RFC 3339 timestamp. Auto-generated by the Writer if empty.
	Timestamp string `json:"timestamp"`

	// SessionID is the session that produced this event (optional).
	SessionID string `json:"session_id,omitempty"`

	// Data holds arbitrary event-specific key-value pairs.
	Data map[string]any `json:"data,omitempty"`
}

// marshalFlat produces a single flat JSON object suitable for JSONL output.
// Top-level fields (event, timestamp, session_id) are merged with Data keys.
//
// If Timestamp is empty, marshalFlat falls back to time.Now().UTC() so that
// standalone marshaling (e.g., via json.Marshal on an Event value) always
// produces a valid timestamp. In normal operation, Writer.AppendEvent sets
// Timestamp via Writer.Now before calling marshalFlat, so the fallback is
// not reached.
func (e Event) marshalFlat() ([]byte, error) {
	if e.EventType == "" {
		return nil, fmt.Errorf("ledger: event type must not be empty")
	}

	m := make(map[string]any, len(e.Data)+3)

	// Copy data fields first so top-level fields take precedence.
	for k, v := range e.Data {
		m[k] = v
	}

	m["event"] = e.EventType

	ts := e.Timestamp
	if ts == "" {
		ts = time.Now().UTC().Format(time.RFC3339)
	}
	m["timestamp"] = ts

	if e.SessionID != "" {
		m["session_id"] = e.SessionID
	}

	return json.Marshal(m)
}

// MarshalJSON produces a single flat JSON object suitable for JSONL output.
// Top-level fields (event, timestamp, session_id) are merged with Data keys.
// If Timestamp is empty, an RFC 3339 timestamp is auto-generated.
func (e Event) MarshalJSON() ([]byte, error) {
	return e.marshalFlat()
}

// UnmarshalJSON parses a flat JSON object into an Event, extracting the
// canonical top-level fields and putting everything else into Data.
func (e *Event) UnmarshalJSON(data []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("ledger: %w", err)
	}

	if v, ok := raw["event"].(string); ok {
		e.EventType = v
		delete(raw, "event")
	}
	if v, ok := raw["timestamp"].(string); ok {
		e.Timestamp = v
		delete(raw, "timestamp")
	}
	if v, ok := raw["session_id"].(string); ok {
		e.SessionID = v
		delete(raw, "session_id")
	}

	if len(raw) > 0 {
		e.Data = raw
	}

	return nil
}
