package githooks

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func testPolicy() *EnforcementPolicy {
	return &EnforcementPolicy{
		ProtectedBranches: []string{"main", "master", "release/*", "production"},
		SensitiveFilePatterns: []string{
			`\.env$`, `\.env\.`, `credentials`, `\.pem$`, `\.key$`,
			`id_rsa`, `id_ed25519`, `\.secret`, `password`,
		},
		GitFormat: GitFormat{
			CommitTypes: []string{
				"feat", "fix", "bugfix", "hotfix", "docs", "refactor",
				"test", "chore", "style", "perf", "build", "ci",
				"revert", "merge", "plan", "refine",
			},
			BranchTypes: []string{
				"feature", "feat", "fix", "bugfix", "hotfix", "release",
				"docs", "refactor", "test", "chore",
			},
			BranchPrefixes: []string{
				"feat/", "fix/", "docs/", "refactor/", "test/", "chore/",
			},
			AIAttributionPatterns: []string{
				"Claude", "Anthropic", "ChatGPT", "Co-Authored-By: Claude",
			},
			Subject: SubjectConfig{
				MaxLength:            50,
				RequireLowercaseType: true,
				ForbidTrailingPeriod: true,
			},
			Body: BodyConfig{
				Format:        "bullets_only",
				MaxBullets:    3,
				LineMaxLength: 72,
			},
		},
	}
}

func TestValidateCommitMsg_ValidMessages(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name string
		msg  string
	}{
		{"simple feat", "feat: add user login"},
		{"docs type", "docs: update README"},
		{"chore type", "chore: update dependencies"},
		{"with bullet body", "feat: add feature\n\n- first change\n- second change"},
		{"single bullet", "fix: resolve bug\n\n- fixed the issue"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if err := ValidateCommitMsg(tt.msg, policy); err != nil {
				t.Errorf("expected valid but got error: %v", err)
			}
		})
	}
}

func TestValidateCommitMsg_SkipConditions(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name string
		msg  string
	}{
		{"merge PR", "Merge pull request #42 from feat/something"},
		{"merge branch", "Merge branch 'main' into feat/something"},
		{"revert", "Revert \"feat: add user login\""},
		{"fixup", "fixup! feat: add user login"},
		{"squash", "squash! feat: add user login"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if err := ValidateCommitMsg(tt.msg, policy); err != nil {
				t.Errorf("expected skip (valid) but got error: %v", err)
			}
		})
	}
}

func TestValidateCommitMsg_EmptyMessage(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name string
		msg  string
	}{
		{"empty string", ""},
		{"only whitespace", "   \n   \n   "},
		{"only comments", "# This is a comment\n# Another comment"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			err := ValidateCommitMsg(tt.msg, policy)
			if err == nil {
				t.Error("expected error for empty message")
			}
		})
	}
}

func TestValidateCommitMsg_AIAttribution(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name    string
		msg     string
		wantErr string
	}{
		{"claude in body", "feat: add feature\n\n- Generated by Claude", "AI attribution"},
		{"chatgpt in body", "feat: add feature\n\n- Written by ChatGPT", "AI attribution"},
		{"co-authored-by claude", "feat: add feature\n\nCo-Authored-By: Claude", "AI attribution"},
		{"case insensitive", "feat: add feature\n\n- ANTHROPIC helped", "AI attribution"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			err := ValidateCommitMsg(tt.msg, policy)
			if err == nil {
				t.Fatal("expected error")
			}
			if !strings.Contains(err.Error(), "AI attribution") && !containsErrorString(err, tt.wantErr) {
				t.Errorf("expected error containing %q, got: %v", tt.wantErr, err)
			}
		})
	}
}

func TestValidateCommitMsg_SubjectLength(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	err := ValidateCommitMsg("feat: "+strings.Repeat("x", 50), policy)
	if err == nil {
		t.Fatal("expected error for long subject")
	}
	if !containsErrorString(err, "subject line too long") {
		t.Errorf("expected 'subject line too long' error, got: %v", err)
	}
}

func TestValidateCommitMsg_InvalidFormat(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name string
		msg  string
	}{
		{"no colon", "feat add something"},
		{"no space after colon", "feat:no space"},
		{"unknown type", "unknown: something"},
		{"missing description", "feat: "},
		{"scoped type", "fix(api): resolve null pointer"},
		{"scoped with hyphen", "fix(my-module): handle edge case"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			err := ValidateCommitMsg(tt.msg, policy)
			if err == nil {
				t.Error("expected error for invalid format")
			}
		})
	}
}

func TestValidateCommitMsg_TrailingPeriod(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	err := ValidateCommitMsg("feat: add something.", policy)
	if err == nil {
		t.Fatal("expected error for trailing period")
	}
	if !containsErrorString(err, "end with a period") {
		t.Errorf("expected 'end with a period' error, got: %v", err)
	}
}

func TestValidateCommitMsg_LowercaseType(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	err := ValidateCommitMsg("Feat: add something", policy)
	if err == nil {
		t.Fatal("expected error for uppercase type")
	}
	if !containsErrorString(err, "lowercase") {
		t.Errorf("expected lowercase error, got: %v", err)
	}
}

func TestValidateCommitMsg_BodyValidation(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	tests := []struct {
		name    string
		msg     string
		wantErr string
	}{
		{
			"missing blank line",
			"feat: something\nbody starts here",
			"missing blank line",
		},
		{
			"non-bullet body",
			"feat: something\n\nThis is not a bullet",
			"non-bullet",
		},
		{
			"too many bullets",
			"feat: something\n\n- one\n- two\n- three\n- four",
			"too many bullet",
		},
		{
			"github squash format",
			"feat: something\n\n* first\n* second",
			"squash-merge",
		},
		{
			"line too long",
			"feat: something\n\n- " + strings.Repeat("x", 72),
			"body line too long",
		},
		{
			"blank between bullets",
			"feat: something\n\n- first\n\n- second",
			"blank lines between bullets",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			err := ValidateCommitMsg(tt.msg, policy)
			if err == nil {
				t.Fatal("expected error")
			}
			if !containsErrorString(err, tt.wantErr) {
				t.Errorf("expected error containing %q, got: %v", tt.wantErr, err)
			}
		})
	}
}

func TestValidateCommitMsg_BodyZeroMaxDefaults(t *testing.T) {
	t.Parallel()

	// With MaxBullets=0 and LineMaxLength=0, defaults to 3 and 72.
	policy := &EnforcementPolicy{
		GitFormat: GitFormat{
			CommitTypes: []string{"feat"},
			Subject:     SubjectConfig{MaxLength: 100},
			Body: BodyConfig{
				MaxBullets:    0,
				LineMaxLength: 0,
			},
		},
	}

	// 4 bullets should fail (default max is 3).
	msg := "feat: test\n\n- one\n- two\n- three\n- four"
	err := ValidateCommitMsg(msg, policy)
	if err == nil {
		t.Fatal("expected error for too many bullets with zero max default")
	}
	if !containsErrorString(err, "too many bullet") {
		t.Errorf("expected 'too many bullet' error, got: %v", err)
	}
}

func TestValidateCommitMsg_EmptyBody(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	// Subject with blank line but no actual body content.
	msg := "feat: test\n\n"
	if err := ValidateCommitMsg(msg, policy); err != nil {
		t.Errorf("expected valid for empty body, got: %v", err)
	}
}

func TestValidateCommitMsg_CommentsStripped(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	msg := "feat: add feature\n# This comment should be stripped\n\n- one change"
	if err := ValidateCommitMsg(msg, policy); err != nil {
		t.Errorf("comments should be stripped, got error: %v", err)
	}
}

func TestValidateCommitMsg_SubjectLengthZeroMax(t *testing.T) {
	t.Parallel()

	// When MaxLength is 0, it defaults to 50.
	policy := &EnforcementPolicy{
		GitFormat: GitFormat{
			Subject: SubjectConfig{MaxLength: 0},
		},
	}
	// 51 chars should fail with default 50.
	longSubject := strings.Repeat("x", 51)
	err := ValidateCommitMsg(longSubject, policy)
	if err == nil {
		t.Fatal("expected error for long subject with zero max")
	}
	if !containsErrorString(err, "subject line too long") {
		t.Errorf("expected 'subject line too long', got: %v", err)
	}
}

func TestValidateCommitMsg_EmptyTypes(t *testing.T) {
	t.Parallel()

	policy := &EnforcementPolicy{
		GitFormat: GitFormat{
			CommitTypes: nil,
			Subject: SubjectConfig{
				MaxLength: 100,
			},
		},
	}
	// With no commit types, format check is skipped — any subject format accepted.
	if err := ValidateCommitMsg("anything goes here", policy); err != nil {
		t.Errorf("expected valid with no types, got: %v", err)
	}
}

func TestValidateCommitMsg_SubjectFormatRegexError(t *testing.T) {
	t.Parallel()

	// Commit types that produce an invalid regex when joined.
	// escapeRegexTypes handles QuoteMeta, but if somehow a type
	// leads to bad regex after wrapping in ^(...)...$, test that path.
	// Since QuoteMeta prevents this, we test the empty types path instead
	// and the regex-compile-fails path by using types with parentheses
	// that break the group structure after escaping.
	// Actually, escapeRegexTypes uses regexp.QuoteMeta so compile should
	// always succeed. The coverage gap is the regex.Compile error return.
	// We'll cover it indirectly; the 88.9% is likely the empty early return.
	// Let's test with types that produce a valid but non-matching pattern.
	policy := &EnforcementPolicy{
		GitFormat: GitFormat{
			CommitTypes: []string{"onlytype"},
			Subject:     SubjectConfig{MaxLength: 100},
		},
	}

	// "feat: test" doesn't match when only "onlytype" is valid.
	err := ValidateCommitMsg("feat: test", policy)
	if err == nil {
		t.Fatal("expected error for unknown type")
	}
	if !containsErrorString(err, "invalid commit format") {
		t.Errorf("expected 'invalid commit format', got: %v", err)
	}
}

func TestRunCommitMsg_ValidFile(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	msgFile := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgFile, []byte("feat: add login"), 0o644); err != nil {
		t.Fatal(err)
	}

	policy := testPolicy()
	if err := RunCommitMsg(msgFile, policy); err != nil {
		t.Errorf("expected valid, got: %v", err)
	}
}

func TestRunCommitMsg_NonexistentFile(t *testing.T) {
	t.Parallel()

	policy := testPolicy()
	err := RunCommitMsg("/nonexistent/path/COMMIT_EDITMSG", policy)
	if err == nil {
		t.Fatal("expected error for nonexistent file")
	}
	if !strings.Contains(err.Error(), "read commit message file") {
		t.Errorf("expected file read error, got: %v", err)
	}
}

func TestRunCommitMsg_InvalidContent(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	msgFile := filepath.Join(dir, "COMMIT_EDITMSG")
	if err := os.WriteFile(msgFile, []byte("BAD FORMAT no colon"), 0o644); err != nil {
		t.Fatal(err)
	}

	policy := testPolicy()
	err := RunCommitMsg(msgFile, policy)
	if err == nil {
		t.Fatal("expected error for invalid content")
	}
}

// containsErrorString checks if err's Error() contains substr, handling
// CommitMsgErrors which collect multiple messages.
func containsErrorString(err error, substr string) bool {
	if err == nil {
		return false
	}
	// Check the full Error() string.
	if strings.Contains(err.Error(), substr) {
		return true
	}
	// Check individual errors in CommitMsgErrors.
	if cmErrs, ok := err.(*CommitMsgErrors); ok {
		for _, e := range cmErrs.Errors {
			if strings.Contains(e, substr) {
				return true
			}
		}
	}
	return false
}
