package githooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// EnforcementPolicy is the subset of enforcement-policy.json used by git hooks.
type EnforcementPolicy struct {
	ProtectedBranches      []string  `json:"protected_branches"`
	SensitiveFilePatterns  []string  `json:"sensitive_file_patterns"`
	GitFormat              GitFormat `json:"git_format"`
}

// GitFormat holds commit and branch formatting rules.
type GitFormat struct {
	CommitTypes           []string       `json:"commit_types"`
	BranchTypes           []string       `json:"branch_types"`
	BranchPrefixes        []string       `json:"branch_prefixes"`
	AIAttributionPatterns []string       `json:"ai_attribution_patterns"`
	Subject               SubjectConfig  `json:"subject"`
	Body                  BodyConfig     `json:"body"`
}

// SubjectConfig holds commit subject line rules.
type SubjectConfig struct {
	MaxLength           int  `json:"max_length"`
	RequireLowercaseType bool `json:"require_lowercase_type"`
	ForbidTrailingPeriod bool `json:"forbid_trailing_period"`
}

// BodyConfig holds commit body rules.
type BodyConfig struct {
	Format       string `json:"format"`
	MaxBullets   int    `json:"max_bullets"`
	LineMaxLength int   `json:"line_max_length"`
}

// LoadEnforcementPolicy reads and parses enforcement-policy.json from
// the given project directory.
func LoadEnforcementPolicy(projectDir string) (*EnforcementPolicy, error) {
	path := filepath.Join(projectDir, ".codeflow", "config", "enforcement", "enforcement-policy.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read enforcement policy: %w", err)
	}

	var policy EnforcementPolicy
	if err := json.Unmarshal(data, &policy); err != nil {
		return nil, fmt.Errorf("parse enforcement policy: %w", err)
	}

	return &policy, nil
}

// DefaultPolicy returns a policy with hardcoded fallback values matching
// the original shell script defaults.
func DefaultPolicy() *EnforcementPolicy {
	return &EnforcementPolicy{
		ProtectedBranches: []string{"main", "master", "release/*", "production"},
		SensitiveFilePatterns: []string{
			`\.env$`,
			`\.env\.`,
			`credentials`,
			`\.pem$`,
			`\.key$`,
			`id_rsa`,
			`id_ed25519`,
			`\.secret`,
			`password`,
		},
		GitFormat: GitFormat{
			CommitTypes: []string{
				"feat", "fix", "bugfix", "hotfix", "docs", "refactor",
				"test", "chore", "style", "perf", "build", "ci",
				"revert", "merge", "plan", "refine",
			},
			BranchTypes: []string{
				"feature", "feat", "fix", "bugfix", "hotfix", "release",
				"docs", "refactor", "test", "chore", "perf", "style",
				"build", "ci", "revert", "plan", "merge", "experiment",
				"wip", "refine",
			},
			BranchPrefixes: []string{
				"feat/", "fix/", "docs/", "refactor/", "test/", "chore/",
				"plan/", "experiment/", "release/", "hotfix/", "bugfix/",
				"feature/", "perf/", "style/", "build/", "ci/", "revert/",
				"merge/", "wip/", "refine/",
			},
			AIAttributionPatterns: []string{
				"Claude", "Anthropic", "@anthropic.com", "claude.ai", "claude code",
				"ChatGPT", "OpenAI", "GPT-3", "GPT-4", "GPT-4o", "o1-preview", "o1-mini",
				"Codex", "@openai.com", "Gemini", "Google AI", "Bard", "@google.com",
				"Copilot", "GitHub Copilot", "@github.com", "Cursor", "Codeium", "Tabnine",
				"CodeWhisperer", "Amazon CodeWhisperer", "Sourcegraph Cody", "Replit AI",
				"Windsurf", "Aider", "Generated with", "Generated by", "AI-generated",
				"AI generated", "Co-Authored-By: AI", "Co-Authored-By: Claude",
				"Co-Authored-By: ChatGPT", "Co-Authored-By: Copilot",
				"\U0001F916", "\U0001F52E", "\u2728 Generated",
			},
			Subject: SubjectConfig{
				MaxLength:            50,
				RequireLowercaseType: true,
				ForbidTrailingPeriod: true,
			},
			Body: BodyConfig{
				Format:        "bullets_only",
				MaxBullets:    3,
				LineMaxLength: 72,
			},
		},
	}
}
