//! The command lookup in `docs/cli.md`, generated from the binary's own clap
//! definitions. The page carries the generated text between two marker
//! comments inside its Technical panel; the test below regenerates it and
//! fails on any difference, and with `CODEFLOW_REGENERATE_LOOKUPS=1` it
//! rewrites the region first, the same route as the other derived lookups.
//!
//! The only authored input is [`JOBS`], the job each subcommand belongs to.
//! A new flag or verb needs nothing here; a new subcommand fails the test
//! until it is placed in a job.

use std::fmt::Write as _;

use clap::{ArgAction, CommandFactory};

/// The derivation name in the page's marker comments.
pub const COMMAND_REFERENCE: &str = "command-reference";

/// The page the lookup is generated into, relative to the repository root.
pub const PAGE: &str = "docs/cli.md";

/// The six jobs, in page order, with the subcommands each one holds.
pub const JOBS: [(&str, &[&str]); 6] = [
    (
        "Scaffold",
        &[
            "init", "update", "epic", "spec", "task", "adr", "ids", "estimate", "feedback",
        ],
    ),
    ("Enforce", &["hook", "git-hook", "ci", "policy", "remote"]),
    (
        "Verify",
        &["test", "validate", "integrate", "doctor", "work"],
    ),
    ("Remember", &["orient", "status", "recall", "report"]),
    ("Delegate", &["delegate", "models"]),
    ("Present", &["portal", "present"]),
];

/// The columns of each generated job table.
pub const COLUMNS: [&str; 3] = ["Command", "Argument or flag", "What it does"];

pub fn begin_marker() -> String {
    format!(
        "<!-- codeflow-derived {COMMAND_REFERENCE} begin: generated by codeflow from the binary; do not edit between the markers. Regenerate with CODEFLOW_REGENERATE_LOOKUPS=1 cargo test -p codeflow-cli derived_lookup -->"
    )
}

pub fn end_marker() -> String {
    format!("<!-- codeflow-derived {COMMAND_REFERENCE} end -->")
}

/// The subcommands `codeflow --help` lists, in its order.
pub fn subcommand_names() -> Vec<String> {
    crate::Cli::command()
        .get_subcommands()
        .filter(|command| !command.is_hide_set())
        .map(|command| command.get_name().to_string())
        .collect()
}

/// A number as the guide writes it in prose, for 0 to 99.
pub fn number_word(n: usize) -> String {
    const ONES: [&str; 20] = [
        "zero",
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
    ];
    const TENS: [&str; 10] = [
        "", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety",
    ];
    match n {
        0..=19 => ONES[n].to_string(),
        20..=99 if n.is_multiple_of(10) => TENS[n / 10].to_string(),
        20..=99 => format!("{}-{}", TENS[n / 10], ONES[n % 10]),
        _ => n.to_string(),
    }
}

/// Help text as one table cell: whitespace folded, pipes escaped, and the
/// dashes and arrows of terminal help written the way the guide writes them.
fn cell(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace(" \u{2014} ", ", ")
        .replace('\u{2014}', ", ")
        .replace('\u{2013}', "-")
        .replace(" -> ", " to ")
        .replace('|', "\\|")
}

fn value_name(arg: &clap::Arg) -> String {
    arg.get_value_names()
        .and_then(|names| names.first())
        .map_or_else(|| arg.get_id().as_str().to_uppercase(), ToString::to_string)
}

fn takes_many(arg: &clap::Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Append)
        || arg
            .get_num_args()
            .is_some_and(|range| range.max_values() > 1)
}

/// How an argument is written: `<NAME>` or `[NAME]` for a positional, the
/// long and short names with the value for an option.
fn usage(arg: &clap::Arg) -> String {
    let many = if takes_many(arg) { "..." } else { "" };
    if arg.is_positional() {
        let name = value_name(arg);
        let name = name.replace('|', "\\|");
        return if arg.is_required_set() {
            format!("`<{name}>{many}`")
        } else {
            format!("`[{name}]{many}`")
        };
    }
    let mut names = Vec::new();
    if let Some(short) = arg.get_short() {
        names.push(format!("-{short}"));
    }
    if let Some(long) = arg.get_long() {
        names.push(format!("--{long}"));
    }
    let takes_value = !matches!(
        arg.get_action(),
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count
    );
    let value = if takes_value {
        format!(" <{}>{many}", value_name(arg))
    } else {
        String::new()
    };
    format!("`{}{value}`", names.join(", ")).replace('|', "\\|")
}

/// What an argument does: its help, then whether it is required, its default
/// and its accepted values when the binary declares them.
fn description(arg: &clap::Arg) -> String {
    let help = arg
        .get_help()
        .or_else(|| arg.get_long_help())
        .map(ToString::to_string)
        .unwrap_or_default();
    let mut text = cell(&help);
    if !text.is_empty() && !text.ends_with(['.', '?', '!']) {
        text.push('.');
    }
    if arg.is_required_set() && !arg.is_positional() {
        text.push_str(" Required.");
    }
    let values: Vec<String> = arg
        .get_possible_values()
        .iter()
        .filter(|value| !value.is_hide_set())
        .map(|value| format!("`{}`", value.get_name()))
        .collect();
    let takes_value = !matches!(
        arg.get_action(),
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count
    );
    if takes_value && !values.is_empty() {
        let _ = write!(text, " One of {}.", values.join(", "));
    }
    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|value| format!("`{}`", value.to_string_lossy()))
        .collect();
    if takes_value && !defaults.is_empty() {
        let _ = write!(text, " Default {}.", defaults.join(", "));
    }
    text.trim().to_string()
}

fn visible_arguments(command: &clap::Command) -> Vec<&clap::Arg> {
    command
        .get_arguments()
        .filter(|arg| {
            !arg.is_hide_set() && !matches!(arg.get_action(), ArgAction::Help | ArgAction::Version)
        })
        .collect()
}

/// The rows for one command and every visible command below it: a row with
/// the command's purpose, then one row per argument or flag. A command that
/// only groups others and takes nothing itself has no row of its own.
fn command_rows(path: &str, command: &clap::Command, rows: &mut Vec<String>) {
    let arguments = visible_arguments(command);
    let children: Vec<&clap::Command> = command
        .get_subcommands()
        .filter(|child| !child.is_hide_set())
        .collect();
    if children.is_empty() || !arguments.is_empty() {
        let about = command
            .get_about()
            .or_else(|| command.get_long_about())
            .map(ToString::to_string)
            .unwrap_or_default();
        let mut name = path.to_string();
        for arg in arguments.iter().filter(|arg| arg.is_positional()) {
            name.push(' ');
            name.push_str(usage(arg).trim_matches('`'));
        }
        rows.push(format!("| `{name}` | | {} |", cell(&about)));
        // A positional the binary says nothing more about is already named
        // in the command cell.
        for arg in &arguments {
            let what = description(arg);
            if arg.is_positional() && what.is_empty() {
                continue;
            }
            rows.push(format!("| | {} | {what} |", usage(arg)));
        }
    }
    for child in children {
        command_rows(&format!("{path} {}", child.get_name()), child, rows);
    }
}

/// The generated region, markers included.
///
/// # Errors
///
/// Names a subcommand that no job holds, or a job entry the binary lacks.
pub fn render() -> Result<String, String> {
    let root = crate::Cli::command();
    let names = subcommand_names();
    for name in &names {
        let placed = JOBS
            .iter()
            .filter(|(_, commands)| commands.contains(&name.as_str()))
            .count();
        if placed != 1 {
            return Err(format!(
                "subcommand {name} is in {placed} jobs; place it in exactly one job in JOBS"
            ));
        }
    }
    let mut text = format!(
        "{}\n\n`codeflow --help` lists {} subcommands. The tables below group them by job and hold each command's purpose and every argument and flag it accepts, in the words of the binary's own help. A required argument is written in angle brackets, an optional one in square brackets, and `...` means it repeats.\n",
        begin_marker(),
        number_word(names.len())
    );
    for (job, commands) in JOBS {
        let mut rows = Vec::new();
        for name in commands {
            let command = root
                .find_subcommand(name)
                .filter(|command| !command.is_hide_set())
                .ok_or_else(|| format!("JOBS names {name}, which the binary does not have"))?;
            command_rows(&format!("codeflow {name}"), command, &mut rows);
        }
        write!(
            text,
            "\n### {job}\n\n| {} |\n|{}\n{}\n",
            COLUMNS.join(" | "),
            "---|".repeat(COLUMNS.len()),
            rows.join("\n")
        )
        .expect("writing to a String cannot fail");
    }
    writeln!(text, "\n{}", end_marker()).expect("writing to a String cannot fail");
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::{Path, PathBuf};

    fn repository() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    /// The region of `page` from the begin marker through the end marker's
    /// line, with what comes before and after it.
    fn split_region(page: &str) -> Option<(&str, &str, &str)> {
        let start = page.find(&begin_marker())?;
        let end_marker = end_marker();
        let end = page[start..].find(&end_marker)? + start + end_marker.len() + 1;
        let end = end.min(page.len());
        Some((&page[..start], &page[start..end], &page[end..]))
    }

    /// `docs/cli.md` holds exactly the lookup the binary generates. With
    /// `CODEFLOW_REGENERATE_LOOKUPS=1` the region is rewritten first; the
    /// authored text around it is kept.
    #[test]
    fn derived_lookup_command_reference_matches_the_binary() {
        let file = repository().join(PAGE);
        let generated = render().unwrap();
        let page = std::fs::read_to_string(&file)
            .unwrap()
            .replace("\r\n", "\n");
        let (before, region, after) = split_region(&page).unwrap_or_else(|| {
            panic!(
                "{PAGE} has no {COMMAND_REFERENCE} markers; add the begin and end marker lines where the lookup belongs"
            )
        });
        if std::env::var_os("CODEFLOW_REGENERATE_LOOKUPS").is_some() {
            std::fs::write(&file, format!("{before}{generated}{after}")).unwrap();
            return;
        }
        assert!(
            region == generated,
            "{PAGE} differs from its {COMMAND_REFERENCE} derivation; run CODEFLOW_REGENERATE_LOOKUPS=1 cargo test -p codeflow-cli derived_lookup"
        );
    }

    #[test]
    fn every_subcommand_has_one_job_and_every_job_entry_exists() {
        render().unwrap();
        let listed: usize = JOBS.iter().map(|(_, commands)| commands.len()).sum();
        assert_eq!(listed, subcommand_names().len());
    }

    #[test]
    fn the_lookup_lists_nested_verbs_flags_and_values() {
        let text = render().unwrap();
        for expected in [
            "| `codeflow init` | | Scaffold this project",
            "| | `--workspace` |",
            "| `codeflow work start <TASK_ID>` |",
            "| `codeflow task new [TITLE]` |",
            "| | `-e, --epic <EPC-NNN>` |",
            "| `codeflow ids check` |",
            "| `codeflow report ceremony` |",
            "One of `ready`, `accepted`, `terminal`.",
        ] {
            assert!(text.contains(expected), "missing {expected}\n{text}");
        }
        // Hidden flags and the auto-generated help stay out.
        assert!(!text.contains("`--help`"));
        assert!(!text.contains('\u{2014}'));
        // Every row has the table's three cells.
        for line in text.lines().filter(|line| line.starts_with("| ")) {
            let cells = line.replace("\\|", "").matches('|').count();
            assert_eq!(cells, COLUMNS.len() + 1, "{line}");
        }
    }

    #[test]
    fn numbers_are_written_as_the_guide_writes_them() {
        assert_eq!(number_word(7), "seven");
        assert_eq!(number_word(19), "nineteen");
        assert_eq!(number_word(20), "twenty");
        assert_eq!(number_word(26), "twenty-six");
    }

    /// The concept figure of the page draws every subcommand once, in the
    /// job the lookup puts it in, so the figure cannot drift from the binary.
    #[test]
    fn the_concept_figure_draws_each_subcommand_in_its_job() {
        let path = repository().join("docs-portal/figures/cli/concept.json");
        let figure: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
        let rows = figure["figure"]["twin"]["rows"].as_array().unwrap();
        let mut drawn: Vec<(String, String)> = Vec::new();
        for row in rows {
            let job = row[0].as_str().unwrap().to_string();
            for column in [1, 2] {
                let text = row[column].as_str().unwrap();
                for name in text.split(", ").filter(|name| *name != "none") {
                    drawn.push((job.clone(), name.trim_matches('`').to_string()));
                }
            }
        }
        let mut expected: Vec<(String, String)> = JOBS
            .iter()
            .flat_map(|(job, commands)| {
                commands
                    .iter()
                    .map(|name| ((*job).to_string(), (*name).to_string()))
            })
            .collect();
        drawn.sort();
        expected.sort();
        assert_eq!(drawn, expected);
    }
}
