id = "SPC-005"
uid = "b18f7920-10c0-4077-beb7-24e8ec34ba6e"
kind = "SPC"
title = "documentation portal utility contract"
issuer = "seed"
created = "2026-09-27T13:28:43Z"
target = "integration/EPC-005-presentation-system"
introduced = "d7518ca12dcc84bb918dd8713d49d67f5e172f80@integration/EPC-005-presentation-system"
landed = "d7518ca12dcc84bb918dd8713d49d67f5e172f80"
mapped = []
mapped_by = "none"
